#!/usr/bin/env python3
"""Build data/source/all-bar-one/ from All Bar One's official allergen & nutrition guide (Mitchells & Butlers).

    python3 tools/uk_extract/all_bar_one.py AllergenGuideAllBarOneEstate.html --checked-on 2026-10-06

Source: https://allergens.mbplc.io/AllergenGuideAllBarOneEstate.html (the page is regenerated by M&B; its header carries
the date). Numbers are copied by tools/uk_extract/mb_guide.py exactly as printed (per portion; kJ is not used).
If All Bar One adds a menu, the script stops until the new menu is listed below as included or excluded.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import mb_guide  # noqa: E402

SOURCE_URL = "https://allergens.mbplc.io/AllergenGuideAllBarOneEstate.html"

MENUS = {
    # The Main Menu is printed three times in the guide (three versions of the same menu); identical rows collapse to one.
    "Main Menu": {"primary": True},
    "Brunch": {},
    "Sharing Plates": {},
    "Bottomless Brunch": {},
    "Small Appetites": {"category": "Small Appetites", "label": "Small Appetites"},
    "Hot Drinks": {},
}
EXCLUDED_MENUS = {
    "Hotel Brunch Menu": "separate hotel brunch menu with its own portion sizes (same dish names, different numbers)",
    "Buffet": "pre-booked party buffet, group portions",
    "Feasting Menu": "pre-booked group package",
    "Tour Menu": "pre-booked tour-group menu",
}

NOTE = ("Cocktails, wines and beers have no nutrition table in the guide, so they are not included. Small Appetites portions are listed "
        "separately; swaps, 'With ...' choices and the hotel, group, buffet and tour menus are not included.")




# Accuracy audit 2026-10-08. The guide prints kJ and kcal for every dish, and for 41 of the 149 dishes they disagree (27 by more than
# 15%: in almost every case the kcal agrees with the printed protein, carbohydrate and fat and the kJ is the odd one out, e.g. Latte
# 645 kJ / 110 kcal, Onion Rings 1569 kJ / 580 kcal). We publish no kJ, but the guide contradicts itself, so these dishes are held back
# (never corrected, never chosen between). Same bands as tools/audit/accuracy_audit.py "high": kJ outside 0.85-1.15 x (kcal x 4.184)
# from 20 kcal, and kcal more than 30% away from 4P+4C+9F for food (mb_guide's own check only stops at 40%). Restoring them is deleting
# this wrapper. The wrapper replaces mb_guide's check for this chain's run only (the module is shared with the other M&B chains).
_impossible_mb = mb_guide._impossible


def _impossible_audited(n: dict, category: str = "") -> str:
    why = _impossible_mb(n, category)
    if why:
        return why
    try:
        kj, kcal = float(n["kj"]), float(n["kcal"])
        prot, carb, fat = (float(str(n[k]).lstrip("<")) for k in ("protein", "carbs", "fat"))
    except (KeyError, ValueError):
        return ""
    if kcal >= 20 and not 0.85 <= kj / (kcal * 4.184) <= 1.15:
        return f"the guide prints {n['kcal']} kcal but {n['kj']} kJ (about {kj / 4.184:.0f} kcal)"
    macro = 4 * prot + 4 * carb + 9 * fat
    if category != "Drinks" and kcal >= 50 and abs(kcal - macro) / kcal > 0.30:
        return f"the guide prints {n['kcal']} kcal; its own protein, carbohydrate and fat add up to about {round(macro)} kcal"
    return ""


mb_guide._impossible = _impossible_audited

if __name__ == "__main__":
    sys.exit(mb_guide.main_for(
        chain_id="all-bar-one", chain_name="All Bar One", cuisine="Bar & Kitchen", aliases=["all bar one", "allbarone"],
        source_url=SOURCE_URL, brand_label="All Bar One", menus=MENUS, excluded_menus=EXCLUDED_MENUS, note=NOTE,
        expected_brand_stamp="All Bar One",
        # in the Main Menu's "Our Favourites" the dishes carry a description; description-less rows there are the choices
        # (bacon, king prawns, ...) printed beside them: add-ons, not meals
        no_desc_sections={"our favourites": "Add-ons"}))
