#!/usr/bin/env python3
"""Build data/source/all-bar-one/ from All Bar One's official allergen & nutrition guide (Mitchells & Butlers).

    python3 tools/uk_extract/all_bar_one.py AllergenGuideAllBarOneEstate.html --checked-on 2026-10-06

Source: https://allergens.mbplc.io/AllergenGuideAllBarOneEstate.html (the page is regenerated by M&B; its header carries
the date). Numbers are copied by tools/uk_extract/mb_guide.py exactly as printed (per portion; kJ is not used).
If All Bar One adds a menu, the script stops until the new menu is listed below as included or excluded.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import mb_guide  # noqa: E402

SOURCE_URL = "https://allergens.mbplc.io/AllergenGuideAllBarOneEstate.html"

MENUS = {
    # The Main Menu is printed three times in the guide (three versions of the same menu); identical rows collapse to one.
    "Main Menu": {"primary": True},
    "Brunch": {},
    "Sharing Plates": {},
    "Bottomless Brunch": {},
    "Small Appetites": {"category": "Small Appetites", "label": "Small Appetites"},
    "Hot Drinks": {},
}
EXCLUDED_MENUS = {
    "Hotel Brunch Menu": "separate hotel brunch menu with its own portion sizes (same dish names, different numbers)",
    "Buffet": "pre-booked party buffet, group portions",
    "Feasting Menu": "pre-booked group package",
    "Tour Menu": "pre-booked tour-group menu",
}

NOTE = ("Cocktails, wines and beers have no nutrition table in the guide, so they are not included. Small Appetites portions are listed "
        "separately; swaps, 'With ...' choices and the hotel, group, buffet and tour menus are not included.")


if __name__ == "__main__":
    sys.exit(mb_guide.main_for(
        chain_id="all-bar-one", chain_name="All Bar One", cuisine="Bar & Kitchen", aliases=["all bar one", "allbarone"],
        source_url=SOURCE_URL, brand_label="All Bar One", menus=MENUS, excluded_menus=EXCLUDED_MENUS, note=NOTE,
        expected_brand_stamp="All Bar One",
        # in the Main Menu's "Our Favourites" the dishes carry a description; description-less rows there are the choices
        # (bacon, king prawns, ...) printed beside them: add-ons, not meals
        no_desc_sections={"our favourites": "Add-ons"}))
