"""Names, categories and flags for Burger King UK's nutrition table, in the PDF's reading order.

ONLY names, grouping and the rankable/note flags are typed by hand here; every number comes from the PDF
(see burger_king_pdf.py). One entry per printed product (each product has a per-serving row and a "per 100g" row;
only the per-serving row is used). `None` = a printed product we deliberately leave out (reason in the comment).

If Burger King adds, removes or reorders rows, burger_king.py stops because the product count no longer matches:
re-check this list against the PDF before running again.
"""

BEEF, CHICKEN, VEG, BREAKFAST, KIDS, SIDES, SWEETS, EXTRAS = (
    "Beef", "Chicken", "Veggie & More", "Breakfast", "Kids", "Sides", "Sweets", "Extras")

# Display order of the categories in the app (main meals first, extras last).
CATEGORY_ORDER = [BEEF, CHICKEN, VEG, BREAKFAST, KIDS, SIDES, SWEETS, EXTRAS]

SHARE = "Guide note: 20 piece serves approximately 4 adults"
SHARER = "Guide note: Sharer box serves approximately 4 adults"
BOX9 = "Nine-burger box (printed serving 1,128 g); not a single-person order, so not suggested"

# Printed products we leave out although they are on the page. Their cells are column-shifted in the PDF (a saturates
# figure larger than the fat figure, a kJ cell holding a fat figure), so no number in the row can be trusted.
EXCLUDED = {
    "Vanilla Milkshake 22oz": "row is column-shifted in the PDF: kJ cell reads 13, saturates 461 g (more than its 9.3 g fat), fat 13/9.3 misplaced",
    "Vanilla Milkshake 12oz": "row is column-shifted in the PDF: kJ cell reads 10, saturates 330 g (more than its 6.9 g fat), sodium printed twice",
}

# (name, category, rankable, note) -- page by page, top to bottom.
ROWS: list[tuple | None] = [
    # ---- page 1: BEEF
    ("Bacon Caesar Angus", BEEF, True, ""),
    ("Bacon Cheeseburger", BEEF, True, ""),
    ("Bacon Double Cheese", BEEF, True, ""),
    ("Bacon Double Cheese XL", BEEF, True, ""),
    ("BBQ Bacon Stacker", BEEF, True, ""),
    ("BBQ Double Melt", BEEF, True, ""),
    ("BBQ Steakhouse Angus", BEEF, True, ""),
    ("Big King", BEEF, True, ""),
    ("Burger Buddies - BBQ Steakhouse", BEEF, True, ""),
    ("Burger Buddies - Big King", BEEF, True, ""),
    ("Burger Buddies - Box 3", BEEF, True, ""),
    ("Burger Buddies - Box 9", BEEF, False, BOX9),
    ("Burger Buddies - Whopper", BEEF, True, ""),
    ("Cheeseburger", BEEF, True, ""),
    ("Classic Double Melts Burger", BEEF, True, ""),
    ("Double Cheeseburger", BEEF, True, ""),
    ("Double Whopper", BEEF, True, ""),
    ("Double Whopper Bacon", BEEF, True, ""),
    ("Double Whopper Bacon & Cheese", BEEF, True, ""),
    ("Double Whopper Cheese", BEEF, True, ""),
    ("Hamburger", BEEF, True, ""),
    ("Texan BBQ King", BEEF, True, ""),
    ("Wellington Wagyu", BEEF, True, ""),
    ("The Wagyu", BEEF, True, ""),
    ("Whopper", BEEF, True, ""),
    ("Whopper Bacon", BEEF, True, ""),
    ("Whopper Bacon & Cheese", BEEF, True, ""),
    ("Whopper Cheese", BEEF, True, ""),
    ("Whopper Jr.", BEEF, True, ""),
    ("Whopper Jr. Cheese", BEEF, True, ""),
    # ---- page 2: BREAKFAST
    ("Bacon & Egg Sandwich (HP Sauce)", BREAKFAST, True, ""),
    ("Bacon & Egg Sandwich (Ketchup)", BREAKFAST, True, ""),
    ("Bacon Butty (HP Sauce)", BREAKFAST, True, ""),
    ("Bacon Butty (Ketchup)", BREAKFAST, True, ""),
    ("Breakfast King (HP Sauce)", BREAKFAST, True, ""),
    ("Breakfast King (Ketchup)", BREAKFAST, True, ""),
    ("Egg & Cheese Breakfast Sandwich", BREAKFAST, True, ""),
    ("Sausage & Egg Sandwich (HP Sauce)", BREAKFAST, True, ""),
    ("Sausage & Egg Sandwich (Ketchup)", BREAKFAST, True, ""),
    ("Sausage Butty (HP Sauce)", BREAKFAST, True, ""),
    ("Sausage Butty (Ketchup)", BREAKFAST, True, ""),
    ("Ultimate Breakfast Sandwich (HP Sauce)", BREAKFAST, True, ""),
    ("Ultimate Breakfast Sandwich (Ketchup)", BREAKFAST, True, ""),
    # ---- page 2: CHICKEN
    ("Bacon Caesar Crispy Chicken", CHICKEN, True, ""),
    ("BBQ Chicken Melts Burger", CHICKEN, True, ""),
    ("BBQ Stacker Chicken Melts Burger Double", CHICKEN, True, ""),
    ("BBQ Stacker Chicken Melts Burger Single", CHICKEN, True, ""),
    ("BBQ Steakhouse Crispy Chicken", CHICKEN, True, ""),
    ("Chicken Royale", CHICKEN, True, ""),
    ("Chicken Royale Double", CHICKEN, True, ""),
    ("Chicken Royale Bacon & Cheese", CHICKEN, True, ""),
    ("Chicken Royale Double with Cheese & Bacon", CHICKEN, True, ""),
    ("Chicken Royale with Cheese", CHICKEN, True, ""),
    ("Chicken Royale Double with Cheese", CHICKEN, True, ""),
    ("Classic Chicken Melts Burger", CHICKEN, True, ""),
    ("Classic Double Chicken Melts Burger", CHICKEN, True, ""),
    ("Steakhouse Crispy Chicken", CHICKEN, True, ""),
    ("Texan BBQ Double Royale", CHICKEN, True, ""),
    ("Texan BBQ Royale", CHICKEN, True, ""),
    # ---- page 3: EXTRAS (ingredients, sauces and toppings; none is a meal)
    ("American Cheese Slice", EXTRAS, False, ""),
    ("Angus Beef Patty", EXTRAS, False, ""),
    ("Back Bacon", EXTRAS, False, ""),
    ("Balsamic Dressing", EXTRAS, False, ""),
    ("BBQ Mayo Style Sauce", EXTRAS, False, ""),
    ("Biscuit Blonde Crumb", EXTRAS, False, ""),
    ("Big King Sauce", EXTRAS, False, ""),
    ("Caesar Dressing", EXTRAS, False, ""),
    ("Caesar Style Sauce", EXTRAS, False, ""),
    ("Caramelised Onion Mayo", EXTRAS, False, ""),
    ("Caramelised Onions", EXTRAS, False, ""),
    ("Cheddar Cheese Sauce", EXTRAS, False, ""),
    ("Chicken Royale Patty", EXTRAS, False, ""),
    ("Chocolate Fudge Biscuit Topping", EXTRAS, False, ""),
    ("Churros", EXTRAS, False, ""),
    ("Cornflake Chicken Patty", EXTRAS, False, ""),
    ("Crispy Chicken Patty", EXTRAS, False, ""),
    ("Crispy Onions", EXTRAS, False, ""),
    ("Diced Bacon", EXTRAS, False, ""),
    ("Egg Patty", EXTRAS, False, ""),
    ("Hamburger Patty", EXTRAS, False, ""),
    ("HP Sauce", EXTRAS, False, ""),
    ("Ketchup", EXTRAS, False, ""),
    ("Lettuce", EXTRAS, False, ""),
    ("Mayonnaise (Egg-Free / Vegan)", EXTRAS, False, ""),
    ("Mint Chocolate Sauce", EXTRAS, False, ""),
    ("Mustard", EXTRAS, False, ""),
    ("Oak Smoked Cheddar Cheese Slice", EXTRAS, False, ""),
    ("Onion Slices", EXTRAS, False, ""),
    ("Pickles", EXTRAS, False, ""),
    # ---- page 4: EXTRAS (continued), KIDS, SIDES (dip pots)
    ("Pink Pickled Onions", EXTRAS, False, ""),
    ("Plant-based Whopper Patty", EXTRAS, False, ""),
    ("Porcini Mushroom Sauce", EXTRAS, False, ""),
    ("Rocket Leaves", EXTRAS, False, ""),
    ("Salted Caramel Sauce", EXTRAS, False, ""),
    ("Salt & Pepper", EXTRAS, False, ""),
    ("Sausage Patty", EXTRAS, False, ""),
    ("Smarties", EXTRAS, False, ""),
    ("Smoky BBQ Sauce", EXTRAS, False, ""),
    ("Sour and Cream Seasoning", EXTRAS, False, ""),
    ("Streaky Bacon", EXTRAS, False, ""),
    ("Texan Style BBQ Sauce", EXTRAS, False, ""),
    ("Tomato Slices", EXTRAS, False, ""),
    ("Truffle Mayo", EXTRAS, False, ""),
    ("Twix Syrup", EXTRAS, False, ""),
    ("Twix Topping", EXTRAS, False, ""),
    ("Vegan Royale Patty", EXTRAS, False, ""),
    ("Wagyu Patty", EXTRAS, False, ""),
    ("Whopper Patty", EXTRAS, False, ""),
    ("Apple Slices", KIDS, True, ""),
    ("Kids Cheeseburger", KIDS, True, ""),
    ("Kids Hamburger", KIDS, True, ""),
    ("Kids Nuggets 4pc", KIDS, True, ""),
    None,  # Whopper Jr. (listed again under KIDS; identical numbers to the BEEF row, so one entry is kept)
    ("BK Dip Pot - Smoky BBQ", SIDES, False, ""),
    ("BK Dip Pot - Spicy Mayo", SIDES, False, ""),
    ("BK Dip Pot - Sweet Chilli", SIDES, False, ""),
    ("BK Dip Pot - BBQ Mayo", SIDES, False, ""),
    ("BK Dip Pot - Flame Grilled Mayo", SIDES, False, ""),
    # ---- page 5: SIDES
    ("BK Dip Pot - Garlic Mayo", SIDES, False, ""),
    ("BK Dip Pot - Spicy Smokehouse Ketchup", SIDES, False, ""),
    ("Texan BBQ Loaded Fries (Delivery exclusive)", SIDES, True, "Delivery exclusive as printed in the guide"),
    ("BBQ Cheese Loaded King Nuggets", SIDES, True, ""),
    ("BBQ Chicken Fries 20pc", SIDES, False, SHARE),
    ("BBQ Chicken Fries 4pc", SIDES, True, ""),
    ("BBQ Chicken Fries 5pc", SIDES, True, ""),
    ("BBQ Chicken Fries 6pc", SIDES, True, ""),
    ("BBQ Chicken Fries 9pc", SIDES, True, ""),
    ("Chicken Nuggets 20pc", SIDES, False, SHARE),
    ("Chicken Nuggets 9pc", SIDES, True, ""),
    ("Chicken Nuggets 6pc", SIDES, True, ""),
    ("Chilli Cheese Bites 20pc", SIDES, False, SHARE),
    ("Chilli Cheese Bites 9pc", SIDES, True, ""),
    ("Chilli Cheese Bites 6pc", SIDES, True, ""),
    ("Fries (regular)", SIDES, True, ""),
    ("Fries (small)", SIDES, True, ""),
    ("Garlic & Jalapeno Chicken Fries 4pc", SIDES, True, ""),
    ("Garlic & Jalapeno Chicken Fries 5pc", SIDES, True, ""),
    ("Garlic & Jalapeno Chicken Fries 6pc", SIDES, True, ""),
    ("Garlic & Jalapeno Chicken Fries 9pc", SIDES, True, ""),
    ("Garlic & Jalapeno Chicken Fries 20pc", SIDES, False, SHARE),
    ("Force Loaded Fries", SIDES, True, ""),
    ("Halloumi Fries 5pc", SIDES, True, ""),
    ("Halloumi Fries 8pc", SIDES, True, ""),
    ("Hash Browns 15pc", SIDES, True, ""),
    ("Hash Browns 28pc", SIDES, True, ""),
    ("Loaded Cheesy King Fries", SIDES, True, ""),
    ("Loaded Cheesy King Fries with Bacon", SIDES, True, ""),
    # ---- page 6: SIDES (continued), SWEETS
    ("Onion Rings 20pc", SIDES, False, SHARE),
    ("Onion Rings 9pc", SIDES, True, ""),
    ("Onion Rings 6pc", SIDES, True, ""),
    ("Salad - Balsamic dressing", SIDES, True, ""),
    ("Salad - Caesar dressing", SIDES, True, ""),
    ("Salad - Plain", SIDES, True, ""),
    ("Sharer Box (5x Garlic and Jalapeno Chicken Fries, Chicken Nuggets, Chilli Cheese Bites and Onion Rings)", SIDES, False, SHARER),
    ("Sharer Box (5x Sour Cream & Onion Chicken Fries, Chicken Nuggets, Chilli Cheese Bites and Onion Rings)", SIDES, False, SHARER),
    ("Sour Cream & Onion Chicken Fries 20pc", SIDES, False, SHARE),
    ("Sour Cream & Onion Chicken Fries 9pc", SIDES, True, ""),
    ("Sour Cream & Onion Chicken Fries 6pc", SIDES, True, ""),
    ("Sour Cream & Onion Chicken Fries 5pc", SIDES, True, ""),
    ("Sour Cream & Onion Chicken Fries 4pc", SIDES, True, ""),
    ("Truffle Loaded Fries", SIDES, True, ""),
    ("Truffle Loaded Nuggets (Delivery exclusive)", SIDES, True, "Delivery exclusive as printed in the guide"),
    ("XL Cheese Dip Pot 65g", SIDES, False, ""),
    ("Ben & Jerry's Caramel Chew Chew 465ml", SWEETS, False, ""),
    ("Ben & Jerry's Fudge Brownie 465ml", SWEETS, False, ""),
    ("Ben & Jerry's Vanilla Cookie Dough 465ml", SWEETS, False, ""),
    ("BK Ice Cream Tubs Chocolate Fudge 100ml", SWEETS, False, ""),
    ("BK Ice Cream Tubs Chocolate Fudge 465ml", SWEETS, False, ""),
    ("Cheesecake Bar - Chocolate Brownie", SWEETS, False, ""),
    ("Cheesecake Bar - Gooey Salted Caramel", SWEETS, False, ""),
    ("Cheesecake Bar - Strawberry Milkshake", SWEETS, False, ""),
    ("Cheesecake Bar - Mango & Passionfruit", SWEETS, False, ""),
    ("Chocolate Milkshake 22oz", SWEETS, False, ""),
    ("Chocolate Milkshake 16oz", SWEETS, False, ""),
    # ---- page 7: SWEETS (continued), VEGGIE & MORE
    ("Chocolate Milkshake 12oz", SWEETS, False, ""),
    ("King Fusion - Plain", SWEETS, False, ""),
    ("Salted Caramel Milkshake 22oz", SWEETS, False, ""),
    ("Salted Caramel Milkshake 16oz", SWEETS, False, ""),
    ("Salted Caramel Milkshake 12oz", SWEETS, False, ""),
    ("Sundae Chocolate", SWEETS, False, ""),
    ("Sundae Plain", SWEETS, False, ""),
    ("Sundae Salted Caramel", SWEETS, False, ""),
    ("Sundae Mint Chocolate", SWEETS, False, ""),
    ("Sundae Strawberry", SWEETS, False, ""),
    ("Smarties King Fusion", SWEETS, False, ""),
    ("Smarties Mini King Fusion", SWEETS, False, ""),
    ("Salted Caramel Churros", SWEETS, False, ""),
    ("Sticky Toffee Churros", SWEETS, False, ""),
    ("Strawberry Milkshake 22oz", SWEETS, False, ""),
    ("Strawberry Milkshake 16oz", SWEETS, False, ""),
    ("Strawberry Milkshake 12oz", SWEETS, False, ""),
    ("Twix Milkshake 16oz", SWEETS, False, ""),
    ("Twix King Fusion", SWEETS, False, ""),
    ("Twix Mini King Fusion", SWEETS, False, ""),
    ("Vanilla Milkshake 22oz", SWEETS, False, ""),
    ("Vanilla Milkshake 16oz", SWEETS, False, ""),
    ("Vanilla Milkshake 12oz", SWEETS, False, ""),
    ("Plant-based Double Whopper", VEG, True, ""),
    ("Plant-based Whopper", VEG, True, ""),
    ("Vegan Royale", VEG, True, ""),
]
