"""Evidence for tools/uk_extract/chaophraya.py: what Chaophraya's CURRENT "Allergens & Calories" pages print, used only to cross-check the
Ten Kites page (nothing here is published; a dish is published only when both agree, see chaophraya.py).

Source: every restaurant page on chaophraya.co.uk (Aberdeen, Birmingham, Edinburgh, Glasgow, Leeds, Newcastle: /thai-restaurant/<town>/menus)
links "ALLERGENS & CALORIES" to its own igfd.menu page (Ingredifind guest menu), e.g. https://igfd.menu/aberdeen/chaophraya-aberdeen-kvmd. The
page's own data feed (gateway.ingredifind.com/menus/get-menu-by-menu-url, loaded by the page itself) carries each dish's "caloriesInKcal" and its
allergen and may-contain lists; the menu list on the page shows no calorie text when it loads. Captured 2026-10-09 with a headless browser, one load per
restaurant, the "A LA CARTE MENU" of each:
  ESTATE     Aberdeen, Birmingham, Glasgow, Leeds and Newcastle all serve the same menu (menu id QaGUFEa5WV5f2ozDKd7p, 74 dishes, identical feeds):
             only 8 dishes carry calories.
  EDINBURGH  its own menu ("A LA CARTE MENU 2026 EDINBURGH", menu id WMPnaEZGSRqsi9Pz8SoY, 76 dishes), with different recipes and 60 dishes carrying calories.
Rows: (section, dish name as printed, calories or None when the dish shows none, contains, may contain). Allergens are the UK 14 only (the feed also lists
non-UK items such as onion-garlic, coconut, citrus, peppers, mushrooms, legumes, kiwi: left out). Names are whitespace-normalised, nothing else.
Both pages mark most dishes verificationStatus UNVERIFIED (the page is the chain's own; the flag is Ingredifind's).

To refresh: load each igfd.menu page in a headless browser (accept the "Continue" notice), save the response of get-menu-by-menu-url, and
rebuild these two lists from its menu.menuSectionsInDisplayOrder[].dishesInDisplayOrder[] (name, caloriesInKcal, allergens, mayContainAllergens).
"""
CAPTURED_ON = "2026-10-09"
ESTATE_URL = "https://igfd.menu/aberdeen/chaophraya-aberdeen-kvmd"
EDINBURGH_URL = "https://igfd.menu/edinburgh/chaophraya-edinburgh-izix"
ESTATE_RESTAURANTS = ["Aberdeen", "Birmingham", "Glasgow", "Leeds", "Newcastle"]
ESTATE = [
    ('NIBBLES', 'KHAO KRIAB GOONG', 559, ['crustaceans'], ['fish', 'gluten']),
    ('NIBBLES', 'KHAO KRIAB GOONG JAY', 254, [], []),
    ('SHARING PLATTERS', 'CHAOPHRAYA PLATTER', None, ['celery', 'crustaceans', 'fish', 'gluten', 'mustard', 'nuts', 'peanuts', 'soya'], ['eggs', 'milk', 'molluscs', 'sesame']),
    ('SHARING PLATTERS', 'TED SAKARN JAY', None, ['celery', 'gluten', 'milk', 'nuts', 'peanuts', 'soya'], []),
    ('SMALL PLATES', 'SATAY CHICKEN', None, ['gluten', 'mustard', 'nuts', 'peanuts'], ['celery', 'crustaceans', 'eggs', 'fish', 'milk', 'molluscs', 'sesame']),
    ('SMALL PLATES', 'POH PIA GAI', None, ['gluten', 'soya'], ['crustaceans', 'eggs', 'fish', 'milk', 'molluscs', 'mustard', 'nuts', 'peanuts', 'sesame']),
    ('SMALL PLATES', 'POH PIA PAK', None, ['gluten', 'soya'], []),
    ('SMALL PLATES', 'GOONG CHOOP PANG TOD', None, ['crustaceans', 'gluten'], []),
    ('SMALL PLATES', 'PAK CHOOP PANG TOD', None, ['celery', 'gluten'], []),
    ('SMALL PLATES', 'TACOS GAI (Chicken)', 307, ['crustaceans', 'fish'], ['celery', 'gluten', 'mustard', 'soya']),
    ('SMALL PLATES', 'TACOS PAK (Vegetable)', 312, ['celery'], ['gluten']),
    ('SMALL PLATES', 'TOD MAN KHAO POHD', None, ['gluten', 'nuts', 'peanuts'], []),
    ('SMALL PLATES', 'MUEK PRIK KLUEA', None, ['gluten', 'molluscs'], []),
    ('SMALL PLATES', 'MOO GROB', None, ['gluten', 'soya'], []),
    ('SALADS', 'SOM TUM', None, ['crustaceans', 'fish', 'gluten', 'milk', 'nuts', 'peanuts'], []),
    ('SALADS', 'SOM TUM JAY', None, ['gluten', 'milk', 'nuts', 'peanuts'], []),
    ('SALADS', 'YUM PED GROB', None, ['celery', 'fish'], []),
    ('RICE & NOODLES', 'KHAO PAD KA PRAO CHICKEN', None, ['crustaceans', 'eggs', 'fish', 'gluten', 'molluscs', 'soya'], []),
    ('RICE & NOODLES', 'KHAO PAD KA PRAO NUEA', None, ['crustaceans', 'eggs', 'fish', 'gluten', 'molluscs', 'soya'], []),
    ('RICE & NOODLES', 'KHAO PAD KA PRAO MOO GROB', None, ['crustaceans', 'eggs', 'fish', 'gluten', 'molluscs', 'soya'], []),
    ('RICE & NOODLES', 'KHAO PAD KA PRAO GOONG', None, ['crustaceans', 'eggs', 'fish', 'gluten', 'molluscs', 'soya'], []),
    ('RICE & NOODLES', 'KHAO PAD SAPPAROD', None, ['crustaceans', 'eggs', 'gluten', 'nuts', 'soya'], ['milk', 'mustard', 'peanuts', 'sesame']),
    ('RICE & NOODLES', 'PAD MEE SUA GAI', None, ['crustaceans', 'eggs', 'fish', 'gluten', 'molluscs', 'soya'], []),
    ('RICE & NOODLES', 'PAD MEE SUA MOO GROB', None, ['crustaceans', 'eggs', 'fish', 'gluten', 'molluscs', 'soya'], []),
    ('RICE & NOODLES', 'PAD MEE SUA VEGAN CHICKEN', None, ['gluten', 'soya'], []),
    ('RICE & NOODLES', 'PAD THAI CHICKEN', None, ['eggs', 'nuts', 'peanuts', 'soya'], ['celery', 'gluten', 'mustard']),
    ('RICE & NOODLES', 'PAD THAI BELLY PORK', None, ['eggs', 'gluten', 'nuts', 'peanuts', 'soya'], ['celery', 'mustard']),
    ('RICE & NOODLES', 'PAD THAI KING PRAWN', None, ['crustaceans', 'eggs', 'nuts', 'peanuts', 'soya'], ['celery', 'gluten', 'mustard']),
    ('RICE & NOODLES', 'PAD THAI TOFU', None, ['celery', 'nuts', 'peanuts', 'soya'], []),
    ('RICE & NOODLES', 'PAD THAI VEGAN CHICKEN', None, ['celery', 'gluten', 'nuts', 'peanuts', 'soya'], []),
    ('THAI SOUPS', 'TOM YUM CHICKEN', None, ['fish', 'milk'], []),
    ('THAI SOUPS', 'TOM YUM KING PRAWN', None, ['crustaceans', 'fish', 'milk'], []),
    ('THAI SOUPS', 'TOM YUM MUSHROOM', None, ['milk'], []),
    ('THAI SOUPS', 'TOM KHA CHICKEN', None, ['soya'], []),
    ('THAI SOUPS', 'TOM KHA KING PRAWN', None, ['crustaceans', 'soya'], []),
    ('THAI SOUPS', 'TOM KHA MUSHROOM', None, ['soya'], []),
    ('CURRY', 'GAENG MASSAMAN GAE', None, ['nuts'], ['gluten', 'milk', 'mustard', 'peanuts', 'sesame', 'soya']),
    ('CURRY', 'GAENG PANANG NUEA', None, [], []),
    ('CURRY', 'KHAO SOI GAI', None, ['crustaceans', 'eggs', 'fish', 'gluten', 'soya'], ['milk', 'mustard', 'nuts', 'peanuts', 'sesame']),
    ('CURRY', 'KHAO SOI NUEA', None, ['crustaceans', 'eggs', 'fish', 'gluten', 'soya'], ['milk', 'mustard', 'nuts', 'peanuts', 'sesame']),
    ('CURRY', 'GAENG KEOW WAN CHICKEN', None, [], []),
    ('CURRY', 'GAENG KEOW WAN VEGAN CHICKEN', None, ['gluten', 'soya'], []),
    ('CURRY', 'GAENG KEOW WAN TOFU', None, ['soya'], []),
    ('CURRY', 'GAENG PED', None, [], []),
    ('CURRY', 'GAENG PED PHAK TONG NAM TAO', None, ['celery'], []),
    ('STIR-FRY', 'PAD KA PRAO CHICKEN', None, ['crustaceans', 'fish', 'gluten', 'molluscs', 'soya'], []),
    ('STIR-FRY', 'PAD KA PRAO BEEF', None, ['crustaceans', 'fish', 'gluten', 'molluscs', 'soya'], []),
    ('STIR-FRY', 'PAD KA PRAO BELLY PORK', None, ['crustaceans', 'fish', 'gluten', 'molluscs', 'soya'], []),
    ('STIR-FRY', 'PAD KA PRAO KING PRAWN', None, ['crustaceans', 'fish', 'gluten', 'molluscs', 'soya'], []),
    ('STIR-FRY', 'MA KUEA PAD KA PRAO', None, ['gluten', 'soya'], []),
    ('STIR-FRY', 'GAI PAD PRIK TAI DUM', None, ['crustaceans', 'fish', 'gluten', 'molluscs', 'soya'], []),
    ('STIR-FRY', 'NUEA PAD PRIK TAI DUM Beef Black Pepper', 861, ['crustaceans', 'fish', 'gluten', 'molluscs', 'soya'], []),
    ('STIR-FRY', 'GAI PAD MET MAMUANG HIMMAPAN', 748, ['celery', 'gluten', 'nuts', 'soya'], ['milk', 'mustard', 'peanuts', 'sesame']),
    ('STIR-FRY', 'PAD MET MAMUANG HIMMAPAN VEGAN CHICKEN', 643, ['celery', 'gluten', 'nuts', 'soya'], ['milk', 'mustard', 'peanuts', 'sesame']),
    ('STIR-FRY', 'PAD MET MAMUANG HIMMAPAN TOFU', 632, ['celery', 'nuts', 'soya'], ['gluten', 'milk', 'mustard', 'peanuts', 'sesame']),
    ('STIR-FRY', 'PAD PREW WAAN CHICKEN', None, ['celery', 'gluten', 'soya'], []),
    ('STIR-FRY', 'PAD PREW WAAN VEGAN CHICKEN', None, ['celery', 'gluten', 'soya'], []),
    ('STIR-FRY', 'PAD PREW WAAN TOFU', None, ['celery', 'gluten', 'soya'], []),
    ('STIR-FRY', 'PLA SAM ROD', None, ['fish', 'gluten'], ['celery', 'mustard', 'soya']),
    ('GRILL', 'SUEA RONG HAI', None, ['crustaceans', 'fish', 'gluten', 'molluscs', 'soya'], []),
    ('GRILL', 'PLA YANG', None, ['crustaceans', 'fish', 'gluten', 'molluscs', 'soya'], []),
    ('GRILL', 'PED YANG NAM MA-KHAM', None, ['nuts'], ['celery', 'gluten', 'milk', 'mustard', 'peanuts', 'sesame', 'soya']),
    ('GRILL', 'GAI GOR-LAE', None, ['fish', 'gluten'], ['milk', 'mustard', 'nuts', 'peanuts', 'sesame', 'soya']),
    ('SIDES', 'KHAO SUAY', None, [], []),
    ('SIDES', 'KHAO PAD KHAI', None, ['eggs'], []),
    ('SIDES', 'KHAO NEOW', None, [], []),
    ('SIDES', 'KHAO MA PRAO', None, ['lupin', 'nuts'], []),
    ('SIDES', 'BA MEE', None, ['eggs', 'gluten', 'soya'], []),
    ('SIDES', 'FIVE SPICE FRIES', None, [], []),
    ('SIDES', 'FIVE SPICE FRIES LOADED WITH RED CURRY CHICKEN', None, ['crustaceans', 'fish'], ['celery', 'gluten', 'mustard', 'soya']),
    ('SIDES', 'FRIES', None, ['eggs', 'mustard'], []),
    ('SIDES', 'TENDERSTEM BROCCOLI', None, ['crustaceans', 'fish', 'gluten', 'molluscs', 'soya'], []),
    ('SIDES', 'PAK CHOI', None, ['crustaceans', 'fish', 'gluten', 'molluscs', 'soya'], []),
    ('SIDES', 'THAI ROTI', None, ['gluten'], []),
]
EDINBURGH = [
    ('SHARING PLATTERS', 'Chaophraya Platter', None, ['crustaceans', 'eggs', 'fish', 'gluten', 'mustard', 'nuts', 'peanuts', 'soya'], ['celery', 'milk', 'molluscs', 'sesame']),
    ('SHARING PLATTERS', 'Ted Sakarn Jay Platter', None, ['celery', 'gluten', 'milk', 'nuts', 'peanuts', 'soya'], []),
    ('SALADS', 'SOM TUM Papaya Salad', 443, ['crustaceans', 'fish', 'gluten', 'nuts', 'peanuts'], ['milk', 'mustard', 'sesame', 'soya']),
    ('SALADS', 'YUM PED Duck Salad', 346, ['fish'], []),
    ('SALADS', 'GOI NUEA Thai Beef Tartare', 341, ['eggs', 'gluten', 'soya'], []),
    ('NIBBLES', 'KHAO KRIAB GOONG', 559, ['crustaceans'], ['fish', 'gluten']),
    ('NIBBLES', 'KHAO KRIAB GOONG JAY', 254, [], []),
    ('SMALL PLATES', 'CHICKEN SATAY (Satay Chaophraya Style)', 323, ['gluten', 'nuts', 'peanuts'], ['milk', 'mustard', 'sesame', 'soya']),
    ('SMALL PLATES', 'POH PIA Chicken Spring Rolls', 322, ['gluten', 'soya'], ['crustaceans', 'eggs', 'fish', 'milk', 'molluscs', 'mustard', 'nuts', 'peanuts', 'sesame']),
    ('SMALL PLATES', 'POH PIA Vegetable Spring Rolls', 338, ['gluten', 'soya'], []),
    ('SMALL PLATES', 'KHANOM JEEB Steamed Dumplings', 326, ['crustaceans', 'eggs', 'gluten', 'soya'], []),
    ('SMALL PLATES', 'GOONG CHOOP PANG TOD Battered King Prawn', 543, ['crustaceans', 'eggs', 'gluten', 'mustard', 'soya'], []),
    ('SMALL PLATES', 'TACOS GAI (Chicken)', 307, ['crustaceans', 'fish'], ['celery', 'gluten', 'mustard', 'soya']),
    ('SMALL PLATES', 'TACOS PAK (Vegetable)', 312, ['celery'], ['gluten']),
    ('SMALL PLATES', 'TOD MAN KHAO POHD Sweetcorn Cakes', 469, ['nuts', 'peanuts'], ['gluten']),
    ('SMALL PLATES', 'MOO SAM CHAN PING Confit Belly Pork Skewers', 1181, ['eggs', 'fish', 'gluten', 'lupin', 'nuts', 'soya'], ['milk', 'mustard', 'peanuts', 'sesame']),
    ('SMALL PLATES', 'MUEK PRIK KLUEA Salt and Pepper Squid', 398, ['eggs', 'gluten', 'molluscs', 'mustard'], []),
    ('SMALL PLATES', 'HOY YANG Seared Scottish King Scallops', 291, ['fish', 'gluten', 'molluscs', 'sesame', 'soya'], ['celery', 'mustard']),
    ('SPECIALITY & GRILL', 'CHOO CHEE HOY YANG King Scallops', 660, ['fish', 'molluscs', 'soya'], []),
    ('SPECIALITY & GRILL', 'KHAO SOI GAI Chiang Mai Curry Noodles Chicken', 1250, ['crustaceans', 'eggs', 'fish', 'gluten', 'soya'], ['milk', 'mustard', 'nuts', 'peanuts', 'sesame']),
    ('SPECIALITY & GRILL', 'Khao Soi Nuea', 1291, ['crustaceans', 'eggs', 'fish', 'gluten', 'soya'], ['milk', 'mustard', 'nuts', 'peanuts', 'sesame']),
    ('SPECIALITY & GRILL', 'SUEA RONG HAI Weeping Tiger', 745, ['crustaceans', 'fish', 'gluten', 'molluscs', 'soya'], []),
    ('SPECIALITY & GRILL', 'PLA YANG (Grilled Sea Bass)', 476, ['crustaceans', 'fish', 'gluten', 'molluscs', 'soya'], []),
    ('SPECIALITY & GRILL', 'GAI GOR-LAE Southern Thai Grilled Chicken', 712, ['fish', 'gluten'], ['milk', 'mustard', 'nuts', 'peanuts', 'sesame', 'soya']),
    ('THAI SOUPS', 'TOM YUM Prawn Hot & Sour Soup', 147, ['crustaceans', 'fish', 'milk', 'soya'], []),
    ('THAI SOUPS', 'TOM YUM Chicken Hot & Sour Soup', 232, ['fish', 'milk', 'soya'], []),
    ('THAI SOUPS', 'TOM YUM Mushroom Hot & Sour Soup', 121, ['milk', 'soya'], []),
    ('THAI SOUPS', 'TOM KHA Chicken Coconut Milk Soup', 264, ['fish', 'soya'], []),
    ('THAI SOUPS', 'TOM KHA Prawn Coconut Milk Soup', 179, ['crustaceans', 'fish', 'soya'], []),
    ('THAI SOUPS', 'TOM KHA Mushroom Coconut Milk Soup', 168, ['soya'], []),
    ('LARGE PLATES', 'GAENG MASSAMAN Royal Lamb Massaman', 969, ['nuts'], ['gluten', 'milk', 'mustard', 'peanuts', 'sesame', 'soya']),
    ('LARGE PLATES', 'GAENG KEOW WAN (Thai Green Chicken)', 692, [], []),
    ('LARGE PLATES', 'GAENG KEOW WAN Thai Green Tofu', 631, ['gluten', 'soya'], []),
    ('LARGE PLATES', 'GAENG PANANG Panang Sous Vide Beef', 794, [], []),
    ('LARGE PLATES', 'GAENG PHED Thai Red Roast Duck', 627, [], []),
    ('LARGE PLATES', 'GAENG PHED Thai Red Tofu', 627, ['gluten', 'soya'], []),
    ('LARGE PLATES', 'PAD THAI King Prawn', 801, ['crustaceans', 'eggs', 'soya'], ['celery', 'gluten', 'mustard']),
    ('LARGE PLATES', 'PAD THAI Chicken', 970, ['eggs', 'soya'], ['celery', 'gluten', 'mustard']),
    ('LARGE PLATES', 'PAD THAI Belly Pork', 1027, ['eggs', 'gluten', 'soya'], ['celery', 'mustard']),
    ('LARGE PLATES', 'PAD THAI Tofu', 921, ['eggs', 'gluten', 'soya'], ['celery', 'mustard']),
    ('LARGE PLATES', 'GAI PAD MET MAMUANG HIMMAPAN', 748, ['celery', 'gluten', 'nuts', 'soya'], ['milk', 'mustard', 'peanuts', 'sesame']),
    ('LARGE PLATES', 'PAD MET MAMUANG HIMMAPAN VEGAN CHICKEN', 643, ['celery', 'gluten', 'nuts', 'soya'], ['milk', 'mustard', 'peanuts', 'sesame']),
    ('LARGE PLATES', 'PAD MET MAMUANG HIMMAPAN TOFU', 632, ['celery', 'nuts', 'soya'], ['gluten', 'milk', 'mustard', 'peanuts', 'sesame']),
    ('LARGE PLATES', 'KHAO PAD SAPPAROD Pineapple Fried Rice Prawn', 628, ['crustaceans', 'eggs', 'gluten', 'nuts', 'soya'], ['milk', 'mustard', 'peanuts', 'sesame']),
    ('LARGE PLATES', 'KHAO PAD SAPPAROD Pineapple Fried Rice Chicken', 795, ['eggs', 'gluten', 'nuts', 'soya'], ['milk', 'mustard', 'peanuts', 'sesame']),
    ('LARGE PLATES', 'KHAO PAD KAPRAO Thai Basil Fried Rice Minced Beef Sirloin', 649, ['crustaceans', 'eggs', 'fish', 'gluten', 'molluscs', 'soya'], []),
    ('LARGE PLATES', 'KHAO PAD KAPRAO Thai Basil Fried Rice Minced Chicken Breast', 552, ['crustaceans', 'eggs', 'fish', 'gluten', 'molluscs', 'soya'], []),
    ('LARGE PLATES', 'KHAO PAD KAPRAO Thai Basil Fried Rice Belly Pork', 688, ['crustaceans', 'eggs', 'fish', 'gluten', 'molluscs', 'soya'], []),
    ('LARGE PLATES', 'KHA PAD KAPRAO Thai Basil Fried Rice Prawn', 501, ['crustaceans', 'eggs', 'fish', 'gluten', 'molluscs', 'soya'], []),
    ('LARGE PLATES', 'PAD KAPRAO (Chilli Thai Basil Minced Beef Sirloin)', 585, ['crustaceans', 'fish', 'gluten', 'molluscs', 'soya'], []),
    ('LARGE PLATES', 'PAD KAPRAO Chilli Thai Basil Minced Chicken', 425, ['crustaceans', 'fish', 'gluten', 'molluscs', 'soya'], []),
    ('LARGE PLATES', 'PAD KAPRAO Chilli Thai Basil Belly Pork', 654, ['crustaceans', 'fish', 'gluten', 'molluscs', 'soya'], []),
    ('LARGE PLATES', 'PAD MEE SUA Stir-Fried Egg Noodles Chicken', 847, ['crustaceans', 'eggs', 'fish', 'gluten', 'molluscs', 'soya'], []),
    ('LARGE PLATES', 'PAD MEE SUA Stir-Fried Egg Noodles Belly Pork', 915, ['crustaceans', 'eggs', 'fish', 'gluten', 'molluscs', 'soya'], []),
    ('LARGE PLATES', 'PAD MEE SUA (Stir-Fried Egg Noodles Vegan Chicken)', 767, ['gluten', 'soya'], []),
    ('LARGE PLATES', 'PAD PRIAO WAN Sweet & Sour Crispy Chicken with Dragon Fruit', 753, ['celery', 'gluten', 'soya'], []),
    ('LARGE PLATES', 'PAD PRIAO WAN (Sweet & Sour Vegan Chicken with Dragon Fruit)', 649, ['celery', 'gluten', 'soya'], []),
    ('LARGE PLATES', 'PAD PRIAON WAN Sweet & Sour Tofu with Dragon Fruit', 638, ['celery', 'gluten', 'soya'], []),
    ('LARGE PLATES', 'NUEA PAD PRIK TAI DUM Beef Black Pepper', 861, ['crustaceans', 'fish', 'gluten', 'molluscs', 'soya'], []),
    ('LARGE PLATES', 'PAD PRIK GAENG MOO GROB Stir-Fried Crispy Pork Belly', 688, ['crustaceans', 'fish', 'gluten', 'molluscs', 'soya'], []),
    ('LARGE PLATES', 'PLA TOD SAM ROD Sea Bass Sam Rod', 649, ['fish', 'gluten'], ['celery', 'mustard', 'soya']),
    ('LARGE PLATES', 'PED YANG NAM-KHAM (Tamarind Roasted Duck)', 881, ['nuts'], ['celery', 'gluten', 'milk', 'mustard', 'peanuts', 'sesame', 'soya']),
    ('SIDES', 'KHAO SUAY', None, [], []),
    ('SIDES', 'KHAO NEOW', None, [], []),
    ('SIDES', 'KHAO MA PRAO', None, ['lupin', 'nuts'], []),
    ('SIDES', 'KHAO PAD KHAI', None, ['eggs'], []),
    ('SIDES', 'BA MEE', None, ['eggs', 'gluten', 'soya'], []),
    ('SIDES', 'FIVE SPICE FRIES', None, [], []),
    ('SIDES', 'FIVE SPICE FRIES LOADED WITH RED CURRY CHICKEN', None, ['crustaceans', 'fish'], ['celery', 'gluten', 'mustard', 'soya']),
    ('SIDES', 'FRIES', None, ['eggs', 'mustard'], []),
    ('SIDES', 'TENDERSTEM BROCCOLI', None, ['crustaceans', 'fish', 'gluten', 'molluscs', 'soya'], []),
    ('SIDES', 'PAK CHOI', None, ['soya'], []),
    ('SIDES', 'THAI ROTI', None, ['gluten'], []),
    ('SHARING SET MENUS', 'Set Chiang Mai', None, ['celery', 'crustaceans', 'eggs', 'fish', 'gluten', 'lupin', 'molluscs', 'mustard', 'nuts', 'peanuts', 'soya'], ['milk', 'sesame']),
    ('SHARING SET MENUS', 'Set Bangkok', None, ['crustaceans', 'eggs', 'fish', 'gluten', 'milk', 'molluscs', 'mustard', 'nuts', 'peanuts', 'soya'], ['celery', 'sesame']),
    ('SHARING SET MENUS', 'Set Phuket', None, ['celery', 'gluten', 'lupin', 'milk', 'nuts', 'peanuts', 'soya'], ['mustard', 'sesame']),
]
