"""Evidence for tools/uk_extract/thaikhun.py: what Thaikhun's CURRENT Allergen & Calorie page prints, used only to cross-check the
Ten Kites page (nothing here is published; a dish is published only when both pages agree).

Source: https://igfd.menu/gateshead/thaikhun-metrocentre-oizg, the page every thaikhun.co.uk restaurant menu page (Aberdeen, Bath, Oxford)
links as "Allergen & Calorie information"; its dish list matches the chain's TK_Main_Menu_AUG26.pdf. Captured with a headless browser
on 2026-10-08 (MAIN MENU, calories switched on; the page's own data feed gave each dish's UK allergens and "may contain").
One entry per dish that shows calories: normalised name -> (name as printed, [calories as printed], (contains, may_contain)) with the
UK 14 allergen keys only (the page also lists non-UK items such as coconut, which are left out). The page marks itself unverified
(verificationStatus UNVERIFIED) and is one restaurant's page (Metrocentre).
"""
CAPTURED_ON = "2026-10-08"
CURRENT_URL = "https://igfd.menu/gateshead/thaikhun-metrocentre-oizg"
CURRENT = {
    'bangkok street': ('Bangkok Street', ['896.583'], (['crustaceans', 'eggs', 'fish', 'gluten', 'molluscs', 'nuts', 'sesame', 'soya'], [])),
    'phuket jay': ('Phuket Jay', ['807'], (['celery', 'gluten', 'nuts', 'peanuts', 'sesame', 'soya'], [])),
    'chicken satay': ('Chicken Satay', ['268.017'], (['gluten', 'mustard', 'nuts', 'peanuts', 'soya'], ['celery', 'crustaceans', 'eggs', 'fish', 'milk', 'molluscs', 'sesame'])),
    'prawn toast': ('Prawn Toast', ['413.181'], (['crustaceans', 'eggs', 'gluten', 'soya'], [])),
    'crispy vegetable gyoza': ('Crispy Vegetable Gyoza', ['305.125'], (['celery', 'gluten', 'sesame', 'soya'], [])),
    'sweetcorn cakes': ('Sweetcorn Cakes', ['523'], (['gluten', 'nuts', 'peanuts'], [])),
    'chicken wings': ('Chicken Wings', ['933.907'], (['fish', 'gluten', 'soya'], [])),
    'thai bbq ribs': ('Thai BBQ Ribs', ['596.738'], (['celery', 'crustaceans', 'fish', 'gluten', 'molluscs', 'soya'], [])),
    'salt and pepper squid': ('Salt & Pepper Squid', ['405.213'], (['gluten', 'molluscs'], [])),
    'thai fish cakes': ('Thai Fish Cakes', ['375'], (['fish', 'nuts', 'peanuts', 'soya'], [])),
    'pork skewers': ('Pork Skewers', ['387.586'], (['crustaceans', 'fish', 'gluten', 'molluscs', 'sesame', 'soya'], ['celery', 'mustard'])),
    'chicken spring rolls': ('Chicken Spring Rolls', ['576.539'], (['gluten', 'nuts', 'sesame', 'soya'], [])),
    'vegetable spring rolls': ('Vegetable Spring Rolls', ['455.538'], (['gluten', 'soya'], [])),
    'thai green chicken': ('Thai Green Chicken', ['696'], ([], [])),
    'thai green beef': ('Thai Green Beef', ['646'], ([], [])),
    'thai green curry prawn': ('Thai Green Curry Prawn', ['501'], (['crustaceans'], [])),
    'thai green curry tofu': ('Thai Green Curry Tofu', ['538'], (['soya'], [])),
    'thai green vegetable': ('Thai Green Vegetable', ['518'], ([], [])),
    'thai green vegan chicken': ('Thai Green Vegan Chicken', ['565'], (['gluten', 'soya'], [])),
    'massaman chicken': ('Massaman Chicken', ['621'], (['gluten', 'nuts'], ['milk', 'mustard', 'peanuts', 'sesame', 'soya'])),
    'massaman beef': ('Massaman Beef', ['772'], (['gluten', 'nuts'], ['milk', 'mustard', 'peanuts', 'sesame', 'soya'])),
    'massaman prawn': ('Massaman Prawn', ['622'], (['crustaceans', 'gluten', 'nuts'], ['milk', 'mustard', 'peanuts', 'sesame', 'soya'])),
    'massaman tofu': ('Massaman Tofu', ['667'], (['gluten', 'nuts', 'soya'], ['milk', 'mustard', 'peanuts', 'sesame'])),
    'massaman vegetable': ('Massaman Vegetable', ['636'], (['gluten', 'nuts'], ['milk', 'mustard', 'peanuts', 'sesame', 'soya'])),
    'massaman vegan chicken': ('Massaman Vegan Chicken', ['693'], (['gluten', 'nuts', 'soya'], ['milk', 'mustard', 'peanuts', 'sesame'])),
    'panang chicken': ('Panang Chicken', ['538'], ([], [])),
    'panang beef': ('Panang Beef', ['618'], ([], [])),
    'panang prawn': ('Panang Prawn', ['472'], (['crustaceans'], [])),
    'panang tofu': ('Panang Tofu', ['516'], (['soya'], [])),
    'panang vegetable': ('Panang Vegetable', ['530'], ([], [])),
    'panang vegan chicken': ('Panang Vegan Chicken', ['546'], (['gluten', 'soya'], [])),
    'thai red chicken': ('Thai Red Chicken', ['486'], ([], [])),
    'thai red beef': ('Thai Red Beef', ['641'], ([], [])),
    'thai red prawn': ('Thai Red Prawn', ['488'], (['crustaceans'], [])),
    'thai red tofu': ('Thai Red Tofu', ['534'], (['soya'], [])),
    'thai red vegetable': ('Thai Red Vegetable', ['521'], ([], [])),
    'thai red vegan chicken': ('Thai Red Vegan Chicken', ['560'], (['gluten', 'soya'], [])),
    'tom yum prawn': ('Tom Yum Prawn', ['233'], (['crustaceans', 'milk', 'soya'], [])),
    'tom yum chicken': ('Tom Yum Chicken', ['234'], (['milk', 'soya'], [])),
    'tom yum mushroom': ('Tom Yum Mushroom', ['208'], (['milk', 'soya'], [])),
    'mee kiew moo daeng': ('Mee Kiew Moo Daeng', ['645'], (['celery', 'crustaceans', 'eggs', 'gluten', 'milk', 'soya'], ['fish', 'sesame'])),
    'legendary ksg': ('Legendary KSG', ['825'], (['eggs', 'fish', 'gluten', 'soya'], ['milk', 'mustard', 'nuts', 'peanuts', 'sesame'])),
    'spicy thai basil fried rice minced chicken': ('Spicy Thai Basil Fried Rice Minced Chicken', ['818'], (['crustaceans', 'eggs', 'fish', 'gluten', 'molluscs', 'soya'], [])),
    'spicy thai basil fried rice minced beef': ('Spicy Thai Basil Fried Rice Minced Beef', ['930'], (['crustaceans', 'eggs', 'fish', 'gluten', 'molluscs', 'soya'], [])),
    'spicy thai basil fried rice belly pork': ('Spicy Thai Basil Fried Rice Belly Pork', ['982'], (['crustaceans', 'eggs', 'fish', 'gluten', 'molluscs', 'soya'], [])),
    'bbq pork on steamed rice': ('BBQ Pork on Steamed Rice', ['596'], (['celery', 'eggs', 'gluten', 'milk', 'sesame', 'soya'], ['fish', 'mustard'])),
    'prawn pineapple fried rice': ('Prawn Pineapple Fried Rice', ['866'], (['crustaceans', 'eggs', 'gluten', 'nuts', 'soya'], ['milk', 'mustard', 'peanuts', 'sesame'])),
    'pad thai chicken': ('Pad Thai Chicken', ['863'], (['eggs', 'nuts', 'peanuts', 'soya'], ['celery', 'gluten', 'mustard'])),
    'pad thai beef': ('Pad Thai Beef', ['1070'], (['eggs', 'nuts', 'peanuts', 'soya'], ['celery', 'gluten', 'mustard'])),
    'pad thai prawn': ('Pad Thai Prawn', ['896'], (['crustaceans', 'eggs', 'nuts', 'peanuts', 'soya'], ['celery', 'gluten', 'mustard'])),
    'pad thai bbq pork': ('Pad Thai BBQ Pork', ['1084'], (['eggs', 'nuts', 'peanuts', 'sesame', 'soya'], ['celery', 'gluten', 'mustard'])),
    'pad thai vegan chicken': ('Pad Thai Vegan Chicken', ['811'], (['celery', 'gluten', 'nuts', 'peanuts', 'soya'], [])),
    'pad thai tofu': ('Pad Thai Tofu', ['942'], (['celery', 'nuts', 'peanuts', 'soya'], [])),
    'street noodles chicken': ('Street Noodles Chicken', ['762.5'], (['crustaceans', 'eggs', 'fish', 'gluten', 'molluscs', 'soya'], [])),
    'street noodles beef': ('Street Noodles Beef', ['794.449'], (['crustaceans', 'eggs', 'fish', 'gluten', 'molluscs', 'soya'], [])),
    'street noodles prawn': ('Street Noodles Prawn', ['632.194'], (['crustaceans', 'eggs', 'fish', 'gluten', 'molluscs', 'soya'], [])),
    'street noodles belly pork': ('Street Noodles Belly Pork', ['857.449'], (['crustaceans', 'eggs', 'fish', 'gluten', 'molluscs', 'soya'], [])),
    'street noodles bbq pork': ('Street Noodles BBQ Pork', ['825.44'], (['crustaceans', 'eggs', 'fish', 'gluten', 'molluscs', 'sesame', 'soya'], ['celery', 'mustard'])),
    'street noodles vegan chicken': ('Street Noodles Vegan Chicken', ['784'], (['gluten', 'soya'], [])),
    'street noodles tofu': ('Street Noodles Tofu', ['646.617'], (['gluten', 'soya'], [])),
    'thai fried rice chicken': ('Thai Fried Rice Chicken', ['521'], (['crustaceans', 'eggs', 'fish', 'gluten', 'molluscs', 'soya'], [])),
    'thai fried rice beef': ('Thai Fried Rice Beef', ['655'], (['crustaceans', 'eggs', 'fish', 'gluten', 'molluscs', 'soya'], [])),
    'thai fried rice prawn': ('Thai Fried Rice Prawn', ['538'], (['crustaceans', 'eggs', 'fish', 'gluten', 'molluscs', 'soya'], [])),
    'thai fried rice belly pork': ('Thai Fried Rice Belly Pork', ['670'], (['crustaceans', 'eggs', 'fish', 'gluten', 'molluscs', 'soya'], [])),
    'thai fried rice vegan chicken': ('Thai Fried Rice Vegan Chicken', ['607'], (['gluten', 'soya'], [])),
    'thai fried rice tofu': ('Thai Fried Rice Tofu', ['591'], (['gluten', 'soya'], [])),
    'thai garlic and black pepper chicken': ('Thai Garlic & Black Pepper Chicken', ['781'], (['crustaceans', 'fish', 'gluten', 'molluscs', 'soya'], [])),
    'thai garlic and black pepper beef': ('Thai Garlic & Black Pepper Beef', ['472'], (['crustaceans', 'fish', 'gluten', 'molluscs', 'soya'], [])),
    'thai garlic and black pepper prawn': ('Thai Garlic & Black Pepper Prawn', ['310'], (['crustaceans', 'fish', 'gluten', 'molluscs', 'soya'], [])),
    'chilli and thai basil minced chicken': ('Chilli & Thai Basil Minced Chicken', ['692'], (['crustaceans', 'eggs', 'fish', 'gluten', 'molluscs', 'soya'], [])),
    'chilli and thai basil minced beef': ('Chilli & Thai Basil Minced Beef', ['566'], (['crustaceans', 'eggs', 'fish', 'gluten', 'molluscs', 'soya'], [])),
    'chilli and thai basil pork belly': ('Chilli & Thai Basil Pork Belly', ['429'], (['crustaceans', 'eggs', 'fish', 'gluten', 'molluscs', 'soya'], [])),
    'chilli and thai basil prawn': ('Chilli & Thai Basil Prawn', ['432'], (['crustaceans', 'eggs', 'fish', 'gluten', 'molluscs', 'soya'], [])),
    'sweet and sour crispy chicken': ('Sweet & Sour Crispy Chicken', ['446'], (['celery', 'gluten', 'soya'], [])),
    'sweet and sour prawn': ('Sweet & Sour Prawn', ['330'], (['celery', 'crustaceans', 'gluten'], [])),
    'sweet and sour tofu': ('Sweet & Sour Tofu', ['451'], (['celery', 'gluten', 'soya'], [])),
    'sweet and sour vegan chicken': ('Sweet & Sour Vegan Chicken', ['458'], (['celery', 'gluten', 'soya'], [])),
    'stir fried cashew nuts crispy chicken': ('Stir-Fried Cashew Nuts Crispy Chicken', ['740'], (['celery', 'gluten', 'nuts', 'soya'], ['milk', 'mustard', 'peanuts', 'sesame'])),
    'stir fried cashew nuts tofu': ('Stir-Fried Cashew Nuts Tofu', ['763'], (['celery', 'nuts', 'soya'], ['gluten', 'milk', 'mustard', 'peanuts', 'sesame'])),
    'stir fried cashew nuts vegan chicken': ('Stir-Fried Cashew Nuts Vegan Chicken', ['725'], (['celery', 'gluten', 'nuts', 'soya'], ['milk', 'mustard', 'peanuts', 'sesame'])),
    'chicken tamarind': ('Chicken Tamarind', ['935'], (['gluten', 'soya'], ['celery', 'mustard'])),
    'stir fried belly pork': ('Stir-Fried Belly Pork', ['804'], (['crustaceans', 'fish', 'gluten', 'molluscs', 'soya'], [])),
    'crispy duck pad kaprao': ('Crispy Duck Pad Kaprao', ['1268'], (['crustaceans', 'fish', 'gluten', 'molluscs', 'soya'], [])),
    'thai chicken katsu': ('Thai Chicken Katsu', ['1389'], (['celery', 'gluten', 'milk', 'soya'], ['fish', 'mustard', 'nuts', 'peanuts', 'sesame'])),
    'seafood udon noodles': ('Seafood Udon Noodles', ['662.561'], (['crustaceans', 'fish', 'gluten', 'molluscs', 'soya'], [])),
    'duck tamarind': ('Duck Tamarind', ['815'], (['nuts'], ['celery', 'gluten', 'milk', 'mustard', 'peanuts', 'sesame', 'soya'])),
    'papaya salad': ('Papaya Salad', ['325.511'], (['crustaceans', 'fish', 'nuts', 'peanuts'], [])),
    'papaya salad vegetarian': ('Papaya Salad Vegetarian', ['349.74'], (['nuts', 'peanuts'], [])),
    'five spice fries': ('Five Spice Fries', ['587'], ([], [])),
    'egg noodles': ('Egg Noodles', ['601'], (['eggs', 'gluten', 'soya'], [])),
    'thai roti': ('Thai Roti', ['292'], (['gluten'], [])),
    'coconut rice': ('Coconut Rice', ['223'], (['lupin', 'nuts'], [])),
    'stir fried vegetable': ('Stir Fried Vegetable', ['203.692'], (['soya'], [])),
    'sticky rice': ('Sticky Rice', ['266'], ([], [])),
    'egg fried rice': ('Egg Fried Rice', ['304'], (['eggs'], [])),
    'jasmine rice': ('Jasmine Rice', ['265'], ([], [])),
    'fries': ('Fries', ['241.944'], ([], [])),
    'mango sticky rice': ('Mango Sticky Rice', ['441'], (['lupin', 'nuts'], [])),
    'banana fritters': ('Banana Fritters', ['586.681'], (['eggs', 'gluten', 'lupin', 'milk', 'nuts', 'sesame'], ['celery', 'mustard'])),
    'chocolate ice cream': ('Chocolate Ice Cream', ['86.063'], (['nuts', 'peanuts', 'soya'], [])),
    'vanilla ice cream': ('Vanilla Ice Cream', ['84.9'], (['soya'], [])),
    'coconut ice cream': ('Coconut Ice Cream', ['108.75'], (['lupin', 'nuts'], [])),
    'mango sorbet': ('Mango Sorbet', ['79.5'], ([], [])),
}
