import { ing, type Recipe } from "../recipes";

// Home-style dinners (British, Italian, batch cooking, one-pan, fish). See lib/mm/recipeBook/index.ts for the rules every recipe follows.

export const DINNER_HOME: readonly Recipe[] = [
  {
    id: "spaghetti-bolognese", meal: "dinner", tags: ["Italian", "Batch cook"], name: "Spaghetti bolognese", blurb: "The family classic with a rich tomato sauce.", servings: 4, minutes: 40,
    ingredients: [ing("beef-mince", 500), ing("passata", 500), ing("chopped-tomato-puree", 30), ing("pasta-long", 320), ing("parmesan", 30)],
    method: [
      "Brown the mince in a large pan, breaking it up with a spoon, until no pink is left.",
      "Stir in the tomato purée and passata and simmer for 20 minutes.",
      "Cook the spaghetti as the pack says.",
      "Serve the sauce on the spaghetti with the cheese grated over.",
    ],
    extras: ["An onion and a carrot", "Garlic", "Dried oregano", "Salt and pepper"],
  },
  {
    id: "beef-lasagne", meal: "dinner", tags: ["Italian", "Bake"], name: "Beef lasagne", blurb: "Layers of meat sauce, pasta and a creamy cheese sauce, baked until bubbling.", servings: 4, minutes: 75,
    ingredients: [ing("beef-mince", 500), ing("passata", 500), ing("chopped-tomato-puree", 30), ing("lasagne-sheets", 200), ing("soft-cheese", 200), ing("milk", 100), ing("mozzarella", 125)],
    method: [
      "Heat the oven to 200°C (180°C fan, gas 6).",
      "Brown the mince in a large pan until no pink is left, then stir in the passata and tomato purée and simmer for 10 minutes.",
      "Beat the soft cheese with the milk until smooth.",
      "In an ovenproof dish, layer a third of the meat sauce, then lasagne sheets, then a little of the cheese sauce. Repeat twice, finishing with cheese sauce.",
      "Tear the mozzarella over the top and bake for 35 to 40 minutes, until golden and bubbling and a knife slides easily through the pasta.",
      "Leave to stand for 5 minutes before cutting.",
    ],
    extras: ["An onion, a carrot and garlic", "Dried oregano or basil", "Salt and pepper"],
  },
  {
    id: "cottage-pie", meal: "dinner", tags: ["British", "Bake"], name: "Cottage pie with cheesy mash", blurb: "Savoury beef mince under a mashed potato top with melted cheddar.", servings: 4, minutes: 60,
    ingredients: [ing("beef-mince", 500), ing("mixed-veg", 195), ing("chopped-tomato-puree", 30), ing("stock-cube", 10), ing("new-potatoes", 800), ing("cheddar", 40)],
    method: [
      "Heat the oven to 200°C (180°C fan, gas 6).",
      "Brown the mince in a large pan until no pink is left.",
      "Stir in the tomato purée, the drained mixed vegetables and the stock cube or pot dissolved in 300 ml of boiling water. Simmer for 15 minutes until thick.",
      "Meanwhile, warm the drained potatoes in a pan of boiling water for 5 minutes, then drain and mash them.",
      "Spoon the mince into an ovenproof dish, spread the mash on top and grate the cheese over.",
      "Bake for 20 to 25 minutes, until golden on top and piping hot.",
    ],
    extras: ["An onion and a carrot", "Dried thyme", "Salt and pepper"],
  },
  {
    id: "chicken-mozzarella-pasta-bake", meal: "dinner", tags: ["Italian", "Bake"], name: "Chicken, tomato and mozzarella pasta bake", blurb: "Pasta, chicken and tomato sauce under bubbling mozzarella.", servings: 4, minutes: 40,
    ingredients: [ing("chicken", 480), ing("pasta-shapes", 300), ing("passata", 500), ing("mozzarella", 125)],
    method: [
      "Heat the oven to 200°C (180°C fan, gas 6). Cook the pasta for 2 minutes less than the pack says, then drain.",
      "Cut the chicken into bite-sized pieces and cook in a hot non-stick pan for 6 to 8 minutes, until cooked through with no pink inside.",
      "Stir in the passata and the pasta, then tip everything into an ovenproof dish.",
      "Tear the mozzarella over the top and bake for 20 minutes, until golden and bubbling.",
    ],
    extras: ["Garlic", "Dried basil or oregano", "A handful of spinach", "A little oil spray"],
  },
  {
    id: "salmon-new-potatoes-peas", meal: "dinner", tags: ["Fish", "Quick"], name: "Salmon with new potatoes and peas", blurb: "Oven-baked salmon with buttery-soft potatoes and sweet peas.", servings: 2, minutes: 25,
    ingredients: [ing("salmon", 280), ing("new-potatoes", 400), ing("peas", 160)],
    method: [
      "Heat the oven to 200°C (180°C fan, gas 6). Put the salmon on a lined baking tray and season it.",
      "Bake for 12 to 15 minutes, until the fish flakes easily.",
      "Meanwhile, warm the drained potatoes in a pan of boiling water for 5 minutes, adding the peas for the last 3 minutes, then drain.",
      "Serve the salmon with the potatoes and peas and a squeeze of lemon.",
    ],
    extras: ["Lemon", "Fresh dill or parsley", "Salt and pepper"],
  },
  {
    id: "pesto-cod-crushed-potatoes", meal: "dinner", tags: ["Fish", "Quick"], name: "Pesto cod with crushed potatoes", blurb: "Cod baked under green pesto with roasted cherry tomatoes.", servings: 2, minutes: 25,
    ingredients: [ing("cod", 300), ing("pesto", 30), ing("new-potatoes", 400), ing("olive-oil", 10)],
    method: [
      "Heat the oven to 200°C (180°C fan, gas 6).",
      "Put the cod on a lined baking tray, spread the pesto over the top and scatter the cherry tomatoes around it.",
      "Bake for 12 to 15 minutes, until the fish flakes easily.",
      "Meanwhile, warm the drained potatoes in boiling water for 5 minutes, drain, then gently crush them with a fork and the olive oil.",
      "Serve the cod and tomatoes on the potatoes, with green beans if you like.",
    ],
    extras: ["Cherry tomatoes", "Green beans", "Salt and pepper"],
  },
  {
    id: "steak-potatoes-peas", meal: "dinner", tags: ["British", "Quick"], name: "Steak with crispy potatoes and peas", blurb: "A pub-style steak dinner made at home.", servings: 2, minutes: 30,
    ingredients: [ing("beef-steak", 400), ing("new-potatoes", 400), ing("peas", 160), ing("olive-oil", 10)],
    method: [
      "Take the steaks out of the fridge 20 minutes before cooking and season them.",
      "Halve the drained potatoes and fry them in half the oil in a non-stick pan for 10 to 12 minutes, turning, until golden.",
      "Cook the peas in boiling water for 3 minutes and drain.",
      "Rub the steaks with the rest of the oil and fry in a very hot pan for 2 to 4 minutes on each side, until browned outside. Cook them a few minutes longer if you want no pink left.",
      "Rest the steaks for 5 minutes, then slice and serve with the potatoes and peas.",
    ],
    extras: ["Garlic", "Fresh thyme or rosemary", "Mustard", "Salt and pepper"],
  },
  {
    id: "chicken-thigh-potato-traybake", meal: "dinner", tags: ["One pan", "British"], name: "Chicken thigh and potato traybake", blurb: "Everything roasts together in one tin.", servings: 4, minutes: 50,
    ingredients: [ing("chicken-thigh", 600), ing("new-potatoes", 800), ing("olive-oil", 15)],
    method: [
      "Heat the oven to 200°C (180°C fan, gas 6).",
      "Put the chicken thighs, the drained potatoes and the sliced onion and peppers in a large roasting tin.",
      "Toss with the oil, paprika, salt and pepper and spread out in one layer.",
      "Roast for 35 to 40 minutes, turning once, until the potatoes are golden and the chicken is cooked through with no pink inside.",
    ],
    extras: ["A red onion and two peppers", "Smoked paprika", "Garlic", "Salt and pepper"],
  },
  {
    id: "baked-gnocchi-tomato-mozzarella", meal: "dinner", tags: ["Italian", "Bake"], name: "Baked gnocchi with tomato and mozzarella", blurb: "Soft gnocchi in tomato sauce under melted mozzarella, no meat.", servings: 3, minutes: 30,
    ingredients: [ing("gnocchi", 500), ing("chopped-tomatoes", 400), ing("mozzarella", 125)],
    method: [
      "Heat the oven to 200°C (180°C fan, gas 6).",
      "Fry the garlic in a pan for a minute, add the chopped tomatoes and simmer for 10 minutes.",
      "Boil the gnocchi for 2 to 3 minutes, until they float, then drain and stir them into the sauce.",
      "Tip into an ovenproof dish, tear the mozzarella over and bake for 15 minutes, until golden and bubbling.",
    ],
    extras: ["Garlic", "Fresh basil", "A little oil spray", "Salt and pepper"],
  },
  {
    id: "easy-macaroni-cheese", meal: "dinner", tags: ["British", "Quick"], name: "Easy macaroni cheese", blurb: "A creamy cheese sauce made in the pasta pan, finished under the grill.", servings: 4, minutes: 25,
    ingredients: [ing("pasta-shapes", 300), ing("soft-cheese", 200), ing("cheddar", 100), ing("milk", 200)],
    method: [
      "Cook the macaroni or other pasta shapes as the pack says, then drain.",
      "In the same pan, warm the milk and soft cheese over a low heat, stirring until smooth.",
      "Take off the heat and stir in most of the grated cheddar, then the pasta.",
      "Tip into an ovenproof dish, scatter over the rest of the cheese and grill for 3 to 5 minutes, until golden.",
    ],
    extras: ["A little mustard", "Black pepper", "Sliced tomatoes for the top"],
  },
  {
    id: "bacon-carbonara-spaghetti", meal: "dinner", tags: ["Italian", "Quick"], name: "Bacon carbonara-style spaghetti", blurb: "Spaghetti in a silky egg and cheese sauce with crispy bacon.", servings: 2, minutes: 20,
    ingredients: [ing("pasta-long", 180), ing("bacon", 150), ing("eggs", 120, { note: "about 2 eggs" }), ing("parmesan", 30)],
    method: [
      "Cook the spaghetti as the pack says. Keep a mugful of the cooking water before you drain it.",
      "Meanwhile, cut the bacon into strips and fry in a non-stick pan until golden.",
      "Beat the eggs with most of the grated cheese and plenty of black pepper.",
      "Tip the drained spaghetti into the bacon pan on a low heat, pour in the egg mix and a splash of the cooking water, and keep stirring for 1 to 2 minutes until the egg is cooked into a thick, creamy sauce.",
      "Serve with the rest of the cheese on top.",
    ],
    extras: ["Black pepper", "Garlic", "Fresh parsley"],
  },
  {
    id: "turkey-meatballs-spaghetti", meal: "dinner", tags: ["Italian", "Batch cook"], name: "Turkey meatballs with spaghetti", blurb: "Herby meatballs simmered in tomato sauce.", servings: 4, minutes: 40,
    ingredients: [ing("turkey-mince", 500), ing("passata", 500), ing("pasta-long", 320)],
    method: [
      "Mix the turkey mince with the garlic, herbs, salt and pepper, and roll into about 16 small balls.",
      "Brown the meatballs in a non-stick pan for 5 minutes, turning them often.",
      "Pour in the passata, cover and simmer for 15 minutes, until the meatballs are cooked through with no pink inside.",
      "Cook the spaghetti as the pack says and serve with the meatballs and sauce.",
    ],
    extras: ["Garlic", "Dried mixed herbs", "Fresh basil", "A little oil spray", "Salt and pepper"],
  },
  {
    id: "shepherds-pie", meal: "dinner", tags: ["British", "Bake"], name: "Shepherd's pie", blurb: "Lamb mince and vegetables under a fluffy mashed potato top.", servings: 4, minutes: 60,
    ingredients: [ing("lamb-mince", 500), ing("mixed-veg", 195), ing("chopped-tomato-puree", 30), ing("stock-cube", 10), ing("new-potatoes", 800)],
    method: [
      "Heat the oven to 200°C (180°C fan, gas 6).",
      "Brown the lamb mince in a large pan until no pink is left, then spoon off any fat.",
      "Add the tomato purée, the drained mixed vegetables and the stock cube or pot dissolved in 300 ml of boiling water. Simmer for 15 minutes until thick.",
      "Meanwhile, warm the drained potatoes in boiling water for 5 minutes, drain and mash them with a splash of the cooking water and black pepper.",
      "Spoon the lamb into an ovenproof dish, spread the mash on top and rough it up with a fork.",
      "Bake for 20 to 25 minutes, until golden on top and piping hot.",
    ],
    extras: ["An onion and a carrot", "Fresh or dried rosemary", "Salt and pepper"],
  },
  {
    id: "lentil-cottage-pie", meal: "dinner", tags: ["British", "Bake"], name: "Lentil cottage pie", blurb: "A meat-free cottage pie with lentils, vegetables and a mashed potato top.", servings: 4, minutes: 55,
    ingredients: [ing("green-lentils", 530), ing("mixed-veg", 195), ing("chopped-tomatoes", 400), ing("chopped-tomato-puree", 30), ing("stock-cube", 10), ing("new-potatoes", 800), ing("olive-oil", 10)],
    method: [
      "Heat the oven to 200°C (180°C fan, gas 6).",
      "Soften the chopped onion and carrot in half the oil in a large pan for 5 minutes.",
      "Add the drained lentils, drained mixed vegetables, chopped tomatoes, tomato purée and the stock cube or pot with 150 ml of boiling water. Simmer for 15 minutes until thick.",
      "Meanwhile, warm the drained potatoes in boiling water for 5 minutes, then drain and mash them with the rest of the oil.",
      "Spoon the lentils into an ovenproof dish, cover with the mash and bake for 20 to 25 minutes, until golden on top.",
    ],
    extras: ["An onion, a carrot and a stick of celery", "Garlic", "Dried thyme", "Salt and pepper"],
  },
  {
    id: "chicken-butter-bean-stew", meal: "dinner", tags: ["One pan", "Batch cook"], name: "Chicken and butter bean stew", blurb: "Chicken and creamy butter beans in a smoky tomato sauce.", servings: 4, minutes: 40,
    ingredients: [ing("chicken", 480), ing("butter-beans", 470, { role: "carb" }), ing("chopped-tomatoes", 400), ing("stock-cube", 10)],
    method: [
      "Cut the chicken into chunks and brown it in a large non-stick pan for 5 minutes.",
      "Add the chopped onion, garlic and paprika and cook for 2 minutes.",
      "Stir in the chopped tomatoes, the drained butter beans and the stock cube or pot with 200 ml of boiling water.",
      "Cover and simmer for 20 minutes, until the chicken is cooked through with no pink inside.",
      "Stir in the spinach until it wilts, then serve.",
    ],
    extras: ["An onion", "Garlic", "Smoked paprika", "A big handful of spinach", "A little oil spray"],
  },
  {
    id: "prawn-tomato-linguine", meal: "dinner", tags: ["Italian", "Fish"], name: "Prawn and tomato linguine", blurb: "King prawns in a garlicky tomato sauce with a little chilli.", servings: 3, minutes: 25,
    ingredients: [ing("prawns", 360), ing("pasta-long", 240), ing("chopped-tomatoes", 400), ing("olive-oil", 10)],
    method: [
      "Cook the linguine as the pack says.",
      "Meanwhile, warm the oil in a large pan and fry the garlic and chilli for a minute.",
      "Add the chopped tomatoes and simmer for 8 minutes.",
      "Add the prawns and cook for 3 to 4 minutes, until piping hot (raw prawns: until pink all the way through).",
      "Toss the drained linguine in the sauce and serve with parsley and a squeeze of lemon.",
    ],
    extras: ["Garlic", "Chilli flakes", "Fresh parsley", "Lemon"],
  },
  {
    id: "halloumi-chickpea-traybake", meal: "dinner", tags: ["One pan", "Bake"], name: "Halloumi and chickpea traybake", blurb: "Roasted potatoes, chickpeas and peppers topped with golden halloumi.", servings: 3, minutes: 45,
    ingredients: [ing("halloumi", 225), ing("chickpeas", 480), ing("new-potatoes", 600), ing("olive-oil", 15)],
    method: [
      "Heat the oven to 200°C (180°C fan, gas 6).",
      "Put the halved drained potatoes, the drained chickpeas and the sliced peppers and onion in a large roasting tin. Toss with the oil and spices and roast for 20 minutes.",
      "Slice the halloumi, lay it on top and roast for another 15 minutes, until the halloumi is golden.",
      "Serve with a squeeze of lemon.",
    ],
    extras: ["Two peppers and a red onion", "Cherry tomatoes", "Smoked paprika and cumin", "Lemon"],
  },
  {
    id: "minestrone-beans-pasta", meal: "dinner", tags: ["Italian", "Batch cook"], name: "Minestrone with beans and pasta", blurb: "A thick Italian vegetable soup with butter beans and pasta.", servings: 3, minutes: 35,
    ingredients: [ing("pasta-shapes", 120), ing("butter-beans", 235), ing("mixed-veg", 195), ing("chopped-tomatoes", 400), ing("stock-cube", 10), ing("olive-oil", 10)],
    method: [
      "Warm the oil in a large pan and soften the chopped onion, carrot and celery for 5 minutes.",
      "Add the chopped tomatoes, the drained mixed vegetables and the stock cube or pot with 750 ml of boiling water. Simmer for 10 minutes.",
      "Add the pasta and drained butter beans and simmer for 10 to 12 minutes, until the pasta is soft.",
      "Season and serve in bowls.",
    ],
    extras: ["An onion, a carrot and a stick of celery", "Garlic", "Fresh basil or dried mixed herbs", "Salt and pepper"],
  },
];
