#!/usr/bin/env python3
"""Build web/lib/mm/halal-data.ts from data/dietary/halal-*.csv (what each chain's OWN website says about halal food).

    python3 tools/dietary/build_halal.py [--check]

Rows: chain_id,scope,statement,source_url,checked_on. Only `all` (the chain says all its UK food/meat is halal) and `some` (some
restaurants or some meat) are published, each with the chain's own words and the page they are on; `no` and `not_stated` are left out.
A row without a quote or a source page is refused (the app never says halal without the restaurant's own words).
"""
from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "data" / "dietary"
OUT = ROOT / "web" / "lib" / "mm" / "halal-data.ts"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    published = {p.name.removeprefix("chain-").removesuffix(".json") for p in (ROOT / "web" / "public" / "menus").glob("chain-*.json")}
    rows: dict[str, dict] = {}
    for f in sorted(SRC.glob("halal-*.csv")):
        for r in csv.DictReader(open(f, newline="", encoding="utf-8")):
            cid, scope = (r.get("chain_id") or "").strip(), (r.get("scope") or "").strip()
            if scope not in ("all", "some"):
                continue
            statement, url = (r.get("statement") or "").strip(), (r.get("source_url") or "").strip()
            if not statement or not url.startswith("https://"):
                print(f"build_halal: {f.name} {cid}: a {scope} row needs the chain's own words and an https page", file=sys.stderr)
                return 1
            if cid not in published:
                print(f"build_halal: skipping {cid} (not a published chain)")
                continue
            rows[cid] = {"scope": scope, "statement": statement, "url": url, "checkedOn": (r.get("checked_on") or "").strip()}
    body = ",\n".join(f"  {json.dumps(k)}: {json.dumps(v, ensure_ascii=False)}" for k, v in sorted(rows.items()))
    ts = (
        "// GENERATED by tools/dietary/build_halal.py from data/dietary/halal-*.csv: do not edit by hand.\n"
        "// What each chain's own website says about halal food (scope \"all\" = all its UK food/meat, \"some\" = some restaurants or some meat).\n"
        "export interface HalalStatement { scope: \"all\" | \"some\"; statement: string; url: string; checkedOn: string }\n\n"
        f"export const HALAL: Readonly<Record<string, HalalStatement>> = {{\n{body}{',' if body else ''}\n}};\n"
    )
    if args.check:
        print(f"{len(rows)} chains: {sum(r['scope'] == 'all' for r in rows.values())} all, {sum(r['scope'] == 'some' for r in rows.values())} some")
        return 0
    OUT.write_text(ts, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(rows)} chains")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
