import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { indexChain } from "../lib/mm/chain-index";
import type { Chain, Nutrients } from "../lib/mm/types";

// Golden fixtures are generated by tools/reference_ranking.py from the fictional sample chains.
const dir = fileURLToPath(new URL("../../data/fixtures/", import.meta.url));

export function loadFixture<T>(name: string): T {
  return JSON.parse(readFileSync(dir + name, "utf8")) as T;
}

export const loadChain = (id: string) => loadFixture<Chain>(`chain-${id}.json`);
export const bowl = () => indexChain(loadChain("bowl-and-co"));
export const cluck = () => indexChain(loadChain("cluck-house"));

/** A tiny in-memory chain for edge cases. Items are given as [id, name, calories, protein, tags?]. */
export function tinyChain(
  items: Array<[string, string, number, number, Chain["items"][number]["tags"]?]>,
  extra: Partial<Chain> = {},
): Chain {
  const nutrients = (calories: number, protein: number): Nutrients => ({ calories, protein, carbs: 10, fat: 5 });
  return {
    schemaVersion: 1,
    id: "tiny",
    name: "Tiny",
    cuisine: "Test",
    builderType: "standard",
    aliases: [],
    sample: true,
    source: { title: "Test", url: "https://example.com", checkedOn: "2026-10-01" },
    categories: ["All"],
    components: [],
    items: items.map(([id, name, calories, protein, tags]) => ({
      id,
      name,
      category: "All",
      serving: "",
      nutrients: nutrients(calories, protein),
      tags: tags ?? [],
      limitedTime: false,
      rankable: true,
      components: [],
      modifiers: [],
    })),
    combinations: [],
    ...extra,
  };
}
