import { chromium } from "playwright-core";
const b = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH });
const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, serviceWorkers: "block" });
const p = await ctx.newPage();
const cdp = await ctx.newCDPSession(p);
await cdp.send("Emulation.setCPUThrottlingRate", { rate: 4 });
await p.addInitScript(() => { window.__lcp = []; new PerformanceObserver((l) => { for (const e of l.getEntries()) window.__lcp.push([Math.round(e.startTime), e.element?.tagName, (e.element?.textContent || "").slice(0, 40), e.element?.className?.toString().slice(0, 40)]); }).observe({ type: "largest-contentful-paint", buffered: true }); });
await p.goto(process.env.BASE + (process.argv[2] || "/app/welcome")); await p.waitForTimeout(4000);
console.log(await p.evaluate(() => window.__lcp), await p.evaluate(() => performance.getEntriesByType("paint").map((e) => [e.name, Math.round(e.startTime)])));
await b.close();
