// GENERATED by tools/dietary/build_halal.py from data/dietary/halal-*.csv: do not edit by hand.
// What each chain's own website says about halal food (scope "all" = all its UK food/meat, "some" = some restaurants or some meat).
export interface HalalStatement { scope: "all" | "some"; statement: string; url: string; checkedOn: string }

export const HALAL: Readonly<Record<string, HalalStatement>> = {

};
