// Official restaurant logos, shown unmodified next to a chain's plain-text name to identify it (founder's decisions
// 2026-10-05 and 2026-10-06, see docs/PROGRESS.md and CLAUDE.md rule 2). A logo appears only if its file is listed here
// AND exists in public/logos/. Nothing is drawn or recreated by us: each file is the chain's own artwork, saved exactly as
// its own website serves it, and its source and terms are recorded in public/logos/SOURCES.md and <id>.source.txt.
// Remove a chain's line to take its logo down.
//
// `tile` is the plain neutral tile the file sits on: "light" (white, the default) or "dark" (near-black) for artwork the
// chain publishes in white for its own dark header. Never a brand colour.

export interface ChainLogo {
  src: string;
  tile?: "light" | "dark";
}

export const CHAIN_LOGOS: Readonly<Record<string, ChainLogo>> = {
  "abokado": { src: "/logos/abokado.png", tile: "dark" },
  "afrikana": { src: "/logos/afrikana.svg", tile: "dark" },
  "all-bar-one": { src: "/logos/all-bar-one.png" },
  "amalfi": { src: "/logos/amalfi.png", tile: "dark" },
  "amigos-burgers-and-shakes": { src: "/logos/amigos-burgers-and-shakes.svg", tile: "dark" },
  "ask-italian": { src: "/logos/ask-italian.svg" },
  "aunties-anne": { src: "/logos/aunties-anne.png" },
  "away-resorts": { src: "/logos/away-resorts.svg" },
  "bagel-factory": { src: "/logos/bagel-factory.svg" },
  "bakers-and-baristas": { src: "/logos/bakers-and-baristas.png", tile: "dark" },
  "banana-tree": { src: "/logos/banana-tree.png", tile: "dark" },
  "barburrito": { src: "/logos/barburrito.png" },
  "baskin-robbins": { src: "/logos/baskin-robbins.png" },
  "baynes": { src: "/logos/baynes.svg" },
  "be-at-one": { src: "/logos/be-at-one.svg", tile: "dark" },
  "bella-italia": { src: "/logos/bella-italia.png", tile: "dark" },
  "bens-cookies": { src: "/logos/bens-cookies.svg" },
  "benugo": { src: "/logos/benugo.svg" },
  "bills": { src: "/logos/bills.svg" },
  "birds-bakery": { src: "/logos/birds-bakery.svg" },
  "bistrot-pierre": { src: "/logos/bistrot-pierre.svg" },
  "blacklock": { src: "/logos/blacklock.svg" },
  "blank-street-coffee": { src: "/logos/blank-street-coffee.svg" },
  "boston-tea-party": { src: "/logos/boston-tea-party.svg", tile: "dark" },
  "brasserie-blanc": { src: "/logos/brasserie-blanc.svg", tile: "dark" },
  "brewdog": { src: "/logos/brewdog.png" },
  "brightside": { src: "/logos/brightside.svg" },
  "british-garden-centres": { src: "/logos/british-garden-centres.png" },
  "browns": { src: "/logos/browns.png" },
  "brunning-and-price": { src: "/logos/brunning-and-price.png" },
  "burger-and-lobster": { src: "/logos/burger-and-lobster.svg" },
  "burger-and-sauce": { src: "/logos/burger-and-sauce.svg" },
  "burger-king": { src: "/logos/burger-king.svg" },
  "burger-shack": { src: "/logos/burger-shack.svg", tile: "dark" },
  "butcombe-inns": { src: "/logos/butcombe-inns.svg" },
  "butlins": { src: "/logos/butlins.png" },
  "buzz-bingo": { src: "/logos/buzz-bingo.png" },
  "cafe-rouge": { src: "/logos/cafe-rouge.png" },
  "caffe-nero": { src: "/logos/caffe-nero.png", tile: "dark" },
  "caravan": { src: "/logos/caravan.svg" },
  "carluccios": { src: "/logos/carluccios.svg", tile: "dark" },
  "castle-carvery": { src: "/logos/castle-carvery.png" },
  "chaiiwala": { src: "/logos/chaiiwala.png" },
  "chilango": { src: "/logos/chilango.svg", tile: "dark" },
  "chipotle": { src: "/logos/chipotle.svg" },
  "chiquito": { src: "/logos/chiquito.svg", tile: "dark" },
  "chopstix": { src: "/logos/chopstix.jpg" },
  "cluckd": { src: "/logos/cluckd.svg" },
  "coco-di-mama": { src: "/logos/coco-di-mama.png", tile: "dark" },
  "coffee-1": { src: "/logos/coffee-1.png" },
  "comptoir-libanais": { src: "/logos/comptoir-libanais.svg" },
  "cooplands": { src: "/logos/cooplands.svg", tile: "dark" },
  "cornish-bakehouse": { src: "/logos/cornish-bakehouse.png", tile: "dark" },
  "cornish-bakery": { src: "/logos/cornish-bakery.png" },
  "cote-brasserie": { src: "/logos/cote-brasserie.svg" },
  "creams-cafe": { src: "/logos/creams-cafe.png", tile: "dark" },
  "daisy-green": { src: "/logos/daisy-green.png" },
  "daves-hot-chicken": { src: "/logos/daves-hot-chicken.svg", tile: "dark" },
  "dim-t": { src: "/logos/dim-t.svg" },
  "drake-and-morgan": { src: "/logos/drake-and-morgan.png" },
  "dunkin": { src: "/logos/dunkin.svg" },
  "eds-easy-diner": { src: "/logos/eds-easy-diner.svg" },
  "ember-inns": { src: "/logos/ember-inns.png" },
  "english-heritage": { src: "/logos/english-heritage.svg" },
  "esquires": { src: "/logos/esquires.svg" },
  "everyman": { src: "/logos/everyman.png" },
  "farmer-j": { src: "/logos/farmer-j.webp" },
  "fat-hippo": { src: "/logos/fat-hippo.svg", tile: "dark" },
  "fishworks": { src: "/logos/fishworks.png", tile: "dark" },
  "five-guys": { src: "/logos/five-guys.svg" },
  "flat-iron": { src: "/logos/flat-iron.svg", tile: "dark" },
  "flight-club": { src: "/logos/flight-club.svg" },
  "forest-holidays": { src: "/logos/forest-holidays.png" },
  "franco-manca": { src: "/logos/franco-manca.svg", tile: "dark" },
  "frankie-and-bennys": { src: "/logos/frankie-and-bennys.svg", tile: "dark" },
  "gails": { src: "/logos/gails.png" },
  "giggling-squid": { src: "/logos/giggling-squid.svg", tile: "dark" },
  "giraffe": { src: "/logos/giraffe.png" },
  "gordon-ramsay-restaurants": { src: "/logos/gordon-ramsay-restaurants.svg", tile: "dark" },
  "gourmet-burger-kitchen": { src: "/logos/gourmet-burger-kitchen.svg" },
  "great-local-pubs": { src: "/logos/great-local-pubs.png" },
  "greene-king": { src: "/logos/greene-king.png", tile: "dark" },
  "greenhalghs": { src: "/logos/greenhalghs.webp", tile: "dark" },
  "greggs": { src: "/logos/greggs.svg" },
  "gusto": { src: "/logos/gusto.webp" },
  "hall-and-woodhouse": { src: "/logos/hall-and-woodhouse.svg" },
  "harbour-hotels": { src: "/logos/harbour-hotels.webp", tile: "dark" },
  "hard-rock-cafe": { src: "/logos/hard-rock-cafe.png" },
  "harvester": { src: "/logos/harvester.png" },
  "haven": { src: "/logos/haven.svg" },
  "heartwood-inns": { src: "/logos/heartwood-inns.svg" },
  "heritage-pubs": { src: "/logos/heritage-pubs.svg", tile: "dark" },
  "hickorys": { src: "/logos/hickorys.svg", tile: "dark" },
  "hoburne-holidays": { src: "/logos/hoburne-holidays.svg", tile: "dark" },
  "hollywood-bowl": { src: "/logos/hollywood-bowl.svg", tile: "dark" },
  "hotel-du-vin": { src: "/logos/hotel-du-vin.svg" },
  "ikea": { src: "/logos/ikea.svg" },
  "itsu": { src: "/logos/itsu.svg" },
  "jamaica-blue": { src: "/logos/jamaica-blue.svg", tile: "dark" },
  "jamies-italian": { src: "/logos/jamies-italian.svg" },
  "jollibee": { src: "/logos/jollibee.webp" },
  "joseph-holt": { src: "/logos/joseph-holt.png" },
  "jw-lees": { src: "/logos/jw-lees.svg" },
  "kfc": { src: "/logos/kfc.svg" },
  "las-iguanas": { src: "/logos/las-iguanas.svg", tile: "dark" },
  "leon": { src: "/logos/leon.svg" },
  "little-dessert-shop": { src: "/logos/little-dessert-shop.png", tile: "dark" },
  "loungers": { src: "/logos/loungers.svg", tile: "dark" },
  "malmaison": { src: "/logos/malmaison.svg", tile: "dark" },
  "maroush": { src: "/logos/maroush.webp" },
  "mcmullens": { src: "/logos/mcmullens.svg", tile: "dark" },
  "megans": { src: "/logos/megans.svg" },
  "mildreds": { src: "/logos/mildreds.png" },
  "miller-and-carter": { src: "/logos/miller-and-carter.png", tile: "dark" },
  "mowgli": { src: "/logos/mowgli.svg" },
  "muffin-break": { src: "/logos/muffin-break.svg", tile: "dark" },
  "mytime-active": { src: "/logos/mytime-active.svg" },
  "nandos": { src: "/logos/nandos.svg" },
  "nicholsons": { src: "/logos/nicholsons.png" },
  "notcutts": { src: "/logos/notcutts.svg" },
  "ole-and-steen": { src: "/logos/ole-and-steen.svg" },
  "oneills": { src: "/logos/oneills.png" },
  "oodles-wok": { src: "/logos/oodles-wok.webp" },
  "park-holidays-uk": { src: "/logos/park-holidays-uk.svg" },
  "parsons-bakery": { src: "/logos/parsons-bakery.webp", tile: "dark" },
  "patisserie-valerie": { src: "/logos/patisserie-valerie.png" },
  "pepes-piri-piri": { src: "/logos/pepes-piri-piri.svg" },
  "pho": { src: "/logos/pho.svg", tile: "dark" },
  "ping-pong": { src: "/logos/ping-pong.svg" },
  "pizza-express": { src: "/logos/pizza-express.svg" },
  "pizza-hut": { src: "/logos/pizza-hut.svg" },
  "pizza-union": { src: "/logos/pizza-union.svg" },
  "places-leisure": { src: "/logos/places-leisure.svg", tile: "dark" },
  "popeyes": { src: "/logos/popeyes.png" },
  "premier-inn": { src: "/logos/premier-inn.svg" },
  "pret": { src: "/logos/pret.png" },
  "prezzo": { src: "/logos/prezzo.svg", tile: "dark" },
  "pubsmiths": { src: "/logos/pubsmiths.svg" },
  "puccinos": { src: "/logos/puccinos.png" },
  "pure": { src: "/logos/pure.png" },
  "puttshack-uk": { src: "/logos/puttshack-uk.svg" },
  "real-greek": { src: "/logos/real-greek.png", tile: "dark" },
  "rick-steins": { src: "/logos/rick-steins.svg" },
  "riva-blu": { src: "/logos/riva-blu.svg" },
  "rockfish": { src: "/logos/rockfish.svg" },
  "rola-wala": { src: "/logos/rola-wala.png" },
  "rosas-thai": { src: "/logos/rosas-thai.svg", tile: "dark" },
  "roxy-leisure": { src: "/logos/roxy-leisure.svg", tile: "dark" },
  "rudys-pizza-napoletana": { src: "/logos/rudys-pizza-napoletana.svg" },
  "sainsburys-cafe": { src: "/logos/sainsburys-cafe.svg" },
  "san-carlo": { src: "/logos/san-carlo.png" },
  "sbarro": { src: "/logos/sbarro.png" },
  "shahs-halal-food": { src: "/logos/shahs-halal-food.png" },
  "showcase-cinemas": { src: "/logos/showcase-cinemas.png", tile: "dark" },
  "sizzling-pubs": { src: "/logos/sizzling-pubs.png" },
  "slim-chickens": { src: "/logos/slim-chickens.svg" },
  "slug-and-lettuce": { src: "/logos/slug-and-lettuce.svg", tile: "dark" },
  "social-pub-and-kitchen": { src: "/logos/social-pub-and-kitchen.svg" },
  "soho-coffee-co": { src: "/logos/soho-coffee-co.png" },
  "starbucks": { src: "/logos/starbucks.svg" },
  "sticks-n-sushi": { src: "/logos/sticks-n-sushi.svg", tile: "dark" },
  "stonehouse": { src: "/logos/stonehouse.png" },
  "strada": { src: "/logos/strada.svg" },
  "taco-bell": { src: "/logos/taco-bell.png" },
  "tenpin": { src: "/logos/tenpin.png" },
  "tgi-fridays": { src: "/logos/tgi-fridays.svg", tile: "dark" },
  "the-botanist": { src: "/logos/the-botanist.svg" },
  "the-breakfast-club": { src: "/logos/the-breakfast-club.png" },
  "the-light-cinemas": { src: "/logos/the-light-cinemas.svg", tile: "dark" },
  "the-restaurant-hub": { src: "/logos/the-restaurant-hub.svg" },
  "third-space": { src: "/logos/third-space.svg" },
  "tim-hortons": { src: "/logos/tim-hortons.png" },
  "toby-carvery": { src: "/logos/toby-carvery.png" },
  "tortilla": { src: "/logos/tortilla.svg", tile: "dark" },
  "village-hotels": { src: "/logos/village-hotels.svg", tile: "dark" },
  "vintage-inns": { src: "/logos/vintage-inns.png" },
  "vue": { src: "/logos/vue.png", tile: "dark" },
  "wagamama": { src: "/logos/wagamama.svg", tile: "dark" },
  "wahaca": { src: "/logos/wahaca.svg", tile: "dark" },
  "warner-hotels": { src: "/logos/warner-hotels.svg" },
  "warrens-bakery": { src: "/logos/warrens-bakery.svg" },
  "wasabi": { src: "/logos/wasabi.svg" },
  "wendys": { src: "/logos/wendys.svg" },
  "wenzels": { src: "/logos/wenzels.svg", tile: "dark" },
  "westmorland-services": { src: "/logos/westmorland-services.svg", tile: "dark" },
  "wetherspoon": { src: "/logos/wetherspoon.svg" },
  "wildwood": { src: "/logos/wildwood.svg" },
  "wimpy": { src: "/logos/wimpy.svg" },
  "yalla-yalla": { src: "/logos/yalla-yalla.webp", tile: "dark" },
  "yo-sushi": { src: "/logos/yo-sushi.svg" },
  "youngs": { src: "/logos/youngs.webp" },
  "zizzi": { src: "/logos/zizzi.svg" },
};

export function logoFor(chainId: string | undefined): ChainLogo | undefined {
  return chainId ? CHAIN_LOGOS[chainId] : undefined;
}
