// Official restaurant logos, shown unmodified next to a chain's plain-text name to identify it (founder's decisions
// 2026-10-05 and 2026-10-06, see docs/PROGRESS.md and CLAUDE.md rule 2). A logo appears only if its file is listed here
// AND exists in public/logos/. Nothing is drawn or recreated by us: each file is the chain's own artwork, saved exactly as
// its own website serves it, and its source and terms are recorded in public/logos/SOURCES.md and <id>.source.txt.
// Remove a chain's line to take its logo down.
//
// `tile` is the plain neutral tile the file sits on: "light" (white, the default) or "dark" (near-black) for artwork the
// chain publishes in white for its own dark header. Never a brand colour.

export interface ChainLogo {
  src: string;
  tile?: "light" | "dark";
}

export const CHAIN_LOGOS: Readonly<Record<string, ChainLogo>> = {
  "abokado": { src: "/logos/abokado.png", tile: "dark" },
  "afrikana": { src: "/logos/afrikana.svg", tile: "dark" },
  "ask-italian": { src: "/logos/ask-italian.svg" },
  "aunties-anne": { src: "/logos/aunties-anne.png" },
  "bagel-factory": { src: "/logos/bagel-factory.svg" },
  "banana-tree": { src: "/logos/banana-tree.png", tile: "dark" },
  "barburrito": { src: "/logos/barburrito.png" },
  "baskin-robbins": { src: "/logos/baskin-robbins.png" },
  "baynes": { src: "/logos/baynes.svg" },
  "be-at-one": { src: "/logos/be-at-one.svg", tile: "dark" },
  "bella-italia": { src: "/logos/bella-italia.png", tile: "dark" },
  "benugo": { src: "/logos/benugo.svg" },
  "bills": { src: "/logos/bills.svg" },
  "birds-bakery": { src: "/logos/birds-bakery.svg" },
  "bistrot-pierre": { src: "/logos/bistrot-pierre.svg" },
  "blank-street-coffee": { src: "/logos/blank-street-coffee.svg" },
  "boston-tea-party": { src: "/logos/boston-tea-party.svg", tile: "dark" },
  "british-garden-centres": { src: "/logos/british-garden-centres.png" },
  "burger-and-lobster": { src: "/logos/burger-and-lobster.svg" },
  "burger-king": { src: "/logos/burger-king.svg" },
  "burger-shack": { src: "/logos/burger-shack.svg", tile: "dark" },
  "cafe-rouge": { src: "/logos/cafe-rouge.png" },
  "caffe-nero": { src: "/logos/caffe-nero.png", tile: "dark" },
  "carluccios": { src: "/logos/carluccios.svg", tile: "dark" },
  "chaiiwala": { src: "/logos/chaiiwala.png" },
  "chilango": { src: "/logos/chilango.svg", tile: "dark" },
  "chipotle": { src: "/logos/chipotle.svg" },
  "chiquito": { src: "/logos/chiquito.svg", tile: "dark" },
  "chopstix": { src: "/logos/chopstix.jpg" },
  "coco-di-mama": { src: "/logos/coco-di-mama.png", tile: "dark" },
  "comptoir-libanais": { src: "/logos/comptoir-libanais.svg" },
  "cooplands": { src: "/logos/cooplands.svg", tile: "dark" },
  "cornish-bakery": { src: "/logos/cornish-bakery.png" },
  "cote-brasserie": { src: "/logos/cote-brasserie.svg" },
  "creams-cafe": { src: "/logos/creams-cafe.png", tile: "dark" },
  "daves-hot-chicken": { src: "/logos/daves-hot-chicken.svg", tile: "dark" },
  "dim-t": { src: "/logos/dim-t.svg" },
  "dunkin": { src: "/logos/dunkin.svg" },
  "eds-easy-diner": { src: "/logos/eds-easy-diner.svg" },
  "english-heritage": { src: "/logos/english-heritage.svg" },
  "esquires": { src: "/logos/esquires.svg" },
  "everyman": { src: "/logos/everyman.png" },
  "farmer-j": { src: "/logos/farmer-j.webp" },
  "fat-hippo": { src: "/logos/fat-hippo.svg", tile: "dark" },
  "five-guys": { src: "/logos/five-guys.svg" },
  "flight-club": { src: "/logos/flight-club.svg" },
  "franco-manca": { src: "/logos/franco-manca.svg", tile: "dark" },
  "frankie-and-bennys": { src: "/logos/frankie-and-bennys.svg", tile: "dark" },
  "gails": { src: "/logos/gails.png" },
  "giggling-squid": { src: "/logos/giggling-squid.svg", tile: "dark" },
  "greene-king": { src: "/logos/greene-king.png", tile: "dark" },
  "greggs": { src: "/logos/greggs.svg" },
  "gusto": { src: "/logos/gusto.webp" },
  "hard-rock-cafe": { src: "/logos/hard-rock-cafe.png" },
  "haven": { src: "/logos/haven.svg" },
  "heartwood-inns": { src: "/logos/heartwood-inns.svg" },
  "hickorys": { src: "/logos/hickorys.svg", tile: "dark" },
  "hollywood-bowl": { src: "/logos/hollywood-bowl.svg", tile: "dark" },
  "hotel-du-vin": { src: "/logos/hotel-du-vin.svg" },
  "ikea": { src: "/logos/ikea.svg" },
  "itsu": { src: "/logos/itsu.svg" },
  "joseph-holt": { src: "/logos/joseph-holt.png" },
  "jw-lees": { src: "/logos/jw-lees.svg" },
  "las-iguanas": { src: "/logos/las-iguanas.svg", tile: "dark" },
  "leon": { src: "/logos/leon.svg" },
  "little-dessert-shop": { src: "/logos/little-dessert-shop.png", tile: "dark" },
  "loungers": { src: "/logos/loungers.svg", tile: "dark" },
  "malmaison": { src: "/logos/malmaison.svg", tile: "dark" },
  "mcmullens": { src: "/logos/mcmullens.svg", tile: "dark" },
  "mowgli": { src: "/logos/mowgli.svg" },
  "notcutts": { src: "/logos/notcutts.svg" },
  "ole-and-steen": { src: "/logos/ole-and-steen.svg" },
  "patisserie-valerie": { src: "/logos/patisserie-valerie.png" },
  "pepes-piri-piri": { src: "/logos/pepes-piri-piri.svg" },
  "pho": { src: "/logos/pho.svg", tile: "dark" },
  "ping-pong": { src: "/logos/ping-pong.svg" },
  "pizza-express": { src: "/logos/pizza-express.svg" },
  "pizza-union": { src: "/logos/pizza-union.svg" },
  "popeyes": { src: "/logos/popeyes.png" },
  "pret": { src: "/logos/pret.png" },
  "prezzo": { src: "/logos/prezzo.svg", tile: "dark" },
  "puccinos": { src: "/logos/puccinos.png" },
  "pure": { src: "/logos/pure.png" },
  "rick-steins": { src: "/logos/rick-steins.svg" },
  "rosas-thai": { src: "/logos/rosas-thai.svg", tile: "dark" },
  "rudys-pizza-napoletana": { src: "/logos/rudys-pizza-napoletana.svg" },
  "san-carlo": { src: "/logos/san-carlo.png" },
  "sbarro": { src: "/logos/sbarro.png" },
  "slim-chickens": { src: "/logos/slim-chickens.svg" },
  "slug-and-lettuce": { src: "/logos/slug-and-lettuce.svg", tile: "dark" },
  "soho-coffee-co": { src: "/logos/soho-coffee-co.png" },
  "starbucks": { src: "/logos/starbucks.svg" },
  "sticks-n-sushi": { src: "/logos/sticks-n-sushi.svg", tile: "dark" },
  "strada": { src: "/logos/strada.svg" },
  "taco-bell": { src: "/logos/taco-bell.png" },
  "tgi-fridays": { src: "/logos/tgi-fridays.svg", tile: "dark" },
  "the-botanist": { src: "/logos/the-botanist.svg" },
  "the-breakfast-club": { src: "/logos/the-breakfast-club.png" },
  "tim-hortons": { src: "/logos/tim-hortons.png" },
  "tortilla": { src: "/logos/tortilla.svg", tile: "dark" },
  "village-hotels": { src: "/logos/village-hotels.svg", tile: "dark" },
  "wagamama": { src: "/logos/wagamama.svg", tile: "dark" },
  "wahaca": { src: "/logos/wahaca.svg", tile: "dark" },
  "warner-hotels": { src: "/logos/warner-hotels.svg" },
  "warrens-bakery": { src: "/logos/warrens-bakery.svg" },
  "wasabi": { src: "/logos/wasabi.svg" },
  "wendys": { src: "/logos/wendys.svg" },
  "wimpy": { src: "/logos/wimpy.svg" },
  "yo-sushi": { src: "/logos/yo-sushi.svg" },
  "zizzi": { src: "/logos/zizzi.svg" },
};

export function logoFor(chainId: string | undefined): ChainLogo | undefined {
  return chainId ? CHAIN_LOGOS[chainId] : undefined;
}
